import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  Brain,
  BrainCircuit,
  Calculator,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  Clock3,
  Coffee,
  Copy,
  Edit3,
  ExternalLink,
  FileText,
  Folder,
  FolderInput,
  FolderPlus,
  History,
  Home,
  Image,
  Info,
  Loader2,
  LogIn,
  LogOut,
  MessageSquare,
  Mic,
  Moon,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  ScanLine,
  Search,
  Send,
  Sparkles,
  Sun,
  Thermometer,
  Timer,
  Trash2,
  Video,
  Volume2,
  Wand2,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import type { IconTone, IconIntensity } from './GlassIconTile';
import type { LucideIcon } from 'lucide-react';

export type IconPresentation = 'hero' | 'primary' | 'action';

export interface IconRegistryEntry {
  icon: LucideIcon;
  tone: IconTone;
  presentation: IconPresentation;
  intensity?: IconIntensity;
  // Backward-safe override. If undefined, derived from presentation.
  useTile?: boolean;
}

const primary = (icon: LucideIcon, tone: IconTone, intensity?: IconIntensity): IconRegistryEntry => ({
  icon,
  tone,
  presentation: 'primary',
  intensity,
});

const action = (icon: LucideIcon, tone: IconTone, intensity: IconIntensity = 'micro'): IconRegistryEntry => ({
  icon,
  tone,
  presentation: 'action',
  intensity,
});

const hero = (icon: LucideIcon, tone: IconTone): IconRegistryEntry => ({
  icon,
  tone,
  presentation: 'hero',
  intensity: 'hero',
});

export const ICON_REGISTRY = {
  Home: primary(Home, 'blue'),
  ScanLine: primary(ScanLine, 'amber'),
  Wrench: primary(Wrench, 'purple'),
  Image: primary(Image, 'green'),
  MessageSquare: primary(MessageSquare, 'blue'),
  Coffee: primary(Coffee, 'amber'),
  PanelLeftClose: action(PanelLeftClose, 'neutral'),
  PanelLeftOpen: action(PanelLeftOpen, 'neutral'),
  Sparkles: hero(Sparkles, 'blue'),
  Camera: primary(Camera, 'amber'),
  Search: action(Search, 'neutral'),
  Loader2: action(Loader2, 'ice'),
  Moon: primary(Moon, 'blue'),
  Sun: primary(Sun, 'amber'),
  LogIn: primary(LogIn, 'ice'),
  LogOut: action(LogOut, 'neutral'),
  X: action(X, 'neutral'),
  Bookmark: action(Bookmark, 'green'),
  BookmarkCheck: action(BookmarkCheck, 'green'),
  Check: action(Check, 'green'),
  Copy: action(Copy, 'ice'),
  ExternalLink: action(ExternalLink, 'ice'),
  BookOpen: primary(BookOpen, 'green'),
  Send: action(Send, 'blue'),
  BrainCircuit: action(BrainCircuit, 'blue'),
  Volume2: action(Volume2, 'ice'),
  Zap: action(Zap, 'amber'),
  Brain: action(Brain, 'purple'),
  Mic: action(Mic, 'purple'),
  Plus: action(Plus, 'neutral'),
  History: primary(History, 'blue'),
  Trash2: action(Trash2, 'neutral'),
  FolderPlus: action(FolderPlus, 'green'),
  Folder: action(Folder, 'green'),
  Edit3: action(Edit3, 'neutral'),
  FolderInput: action(FolderInput, 'green'),
  MoreHorizontal: action(MoreHorizontal, 'neutral'),
  Wand2: action(Wand2, 'blue'),
  ChevronDown: action(ChevronDown, 'neutral'),
  ChevronRight: action(ChevronRight, 'neutral'),
  AlertCircle: action(AlertCircle, 'amber'),
  ArrowLeft: action(ArrowLeft, 'neutral'),
  FileText: action(FileText, 'neutral'),
  RefreshCw: action(RefreshCw, 'ice'),
  Video: action(Video, 'amber'),
  CheckCircle: action(CheckCircle, 'green'),
  AlertTriangle: action(AlertTriangle, 'amber'),
  Calculator: primary(Calculator, 'purple'),
  CheckSquare: primary(CheckSquare, 'green'),
  Clock3: primary(Clock3, 'ice'),
  Info: action(Info, 'ice'),
  Pause: action(Pause, 'amber'),
  Play: action(Play, 'green'),
  RotateCcw: action(RotateCcw, 'neutral'),
  Thermometer: primary(Thermometer, 'amber'),
  Timer: primary(Timer, 'purple'),
} satisfies Record<string, IconRegistryEntry>;
