import { DEFAULT_LANGUAGE, getLanguageLocale, isSupportedLanguage } from '../constants';
import type { Language } from '../types';

const EN_ADMIN_COPY = {
  accessRequiredTitle: 'Admin access required',
  accessRequiredAuth: 'Sign in with an owner account to open the management console.',
  accessRequiredForbidden: 'Your current account is not in ADMIN_EMAILS or ADMIN_USER_IDS.',
  adminRequestFailed: 'Admin request failed',
  signIn: 'Sign in',
  retry: 'Retry',
  dismissAdminError: 'Dismiss admin error',
  pageTitle: 'Admin Management',
  pageSubtitle: 'Users, plans, database readiness, audit, and launch control.',
  backToApp: 'App',
  backToAppTitle: 'Back to application',
  switchToLight: 'Switch admin to light mode',
  switchToDark: 'Switch admin to dark mode',
  light: 'Light',
  dark: 'Dark',
  refresh: 'Refresh',
  live: 'Live',
  tabOverview: 'Command',
  tabUsers: 'Users',
  tabPlans: 'Plans',
  tabMaintenance: 'Maintenance',
  tabDatabase: 'Database',
  tabAudit: 'Audit',
  tabLaunch: 'Launch',
  metricTotalUsers: 'Total Users',
  metricPaidUsers: 'Paid Users',
  metricAiToday: 'AI Today',
  metricLaunchGate: 'Launch Gate',
  activeAccounts: '{count} active accounts',
  planConversion: '{count}% plan conversion',
  deepRequests: '{count} deep requests',
  criticalWarnings: 'Critical failures / warnings',
  exportTitle: 'Operator export deck',
  exportSubtitle: 'Download the current account roster, audit trail, or copy a launch handoff summary for support and founders.',
  usersCsv: 'Users CSV',
  auditCsv: 'Audit CSV',
  copyHandoff: 'Copy handoff',
  snapshot: 'Snapshot',
  freshness: 'Freshness',
  queues: 'Queues',
  flags: 'Flags',
  queueRisk: 'Risk queue',
  queueRecovery: 'Recovery queue',
  queueBilling: 'Billing attention',
  queuePaid: 'Paid users',
  queueSample: 'Preview data',
  queueAll: 'All queues',
  commandCenterTitle: 'Operations command center',
  commandCenterSubtitle: 'Prioritized queues for account support, launch blockers, and live maintenance response.',
  riskCardTitle: 'Risk queue',
  riskCardDetail: '{count} past-due plus suspended or high-risk accounts.',
  recoveryCardTitle: 'Recovery',
  recoveryCardDetail: 'Password reset and account recovery requests.',
  billingCardTitle: 'Billing',
  billingCardDetail: 'Payment action, refund, expired, and past-due reviews.',
  flagsCardTitle: 'Flags',
  flagsCardDetail: 'Active web, PWA, mobile, or admin maintenance controls.',
  paidCardTitle: 'Paid',
  paidCardDetail: 'Starter, Pro, Team, and Enterprise accounts.',
  handoffTitle: 'Operator handoff',
  noUrgentHandoff: 'No urgent handoff',
  queuesClear: 'Risk and recovery queues are clear.',
  productionChecks: 'Production checks',
  productionChecksSubtitle: 'Current backend, database, billing, and AI readiness.',
  planMix: 'Plan mix',
  recommendations: 'Recommendations',
  usersSearchPlaceholder: 'Search name, username, email, or user id',
  allStatus: 'All status',
  allPlans: 'All plans',
  allRecovery: 'All recovery',
  noMatchingUsers: 'No matching users',
  noMatchingUsersSubtitle: 'Adjust search, status, or plan filters.',
  account: 'Account',
  status: 'Status',
  plan: 'Plan',
  billing: 'Billing',
  role: 'Role',
  recovery: 'Recovery',
  usageToday: 'Usage today',
  risk: 'Risk',
  lastSeen: 'Last seen',
  manage: 'Manage',
  preview: 'preview',
  unassigned: 'unassigned',
  unknown: 'Unknown',
  localeNA: 'locale n/a',
  actionRequired: 'Action required',
  passwordResetRequired: 'Password reset required',
  saving: 'Saving...',
  savingAccount: 'Saving account...',
  accountControl: 'Account control',
  closeAccountPanel: 'Close account panel',
  created: 'Created',
  currentPlan: 'Current plan',
  displayName: 'Display name',
  username: 'Username',
  adminQuickActions: 'Admin quick actions',
  adminQuickActionsSubtitle: 'Use these for the common launch-support flows without hunting through every field.',
  restoreActive: 'Restore active',
  suspendReview: 'Suspend review',
  planQuickControl: 'Plan quick control',
  planQuickControlSubtitle: 'Pick a tier, see the quota, then apply entitlement with a review-ready support note.',
  provider: 'Provider',
  market: 'Market',
  manualReview: 'manual review',
  selected: 'selected',
  applyProvisional: 'Apply provisional',
  applyFree: 'Apply free',
  billingEntitlement: 'Billing and entitlement',
  receiptModeDetail: 'Receipt mode applies {limit} immediately, then keeps manual review required until the subscription is verified.',
  billingStatus: 'Billing status',
  paymentActionRequired: 'Payment action required',
  receiptReceived: 'Receipt received',
  markPaid: 'Mark paid',
  markPastDue: 'Mark past due',
  customer: 'Customer',
  subscription: 'Subscription',
  renewsEnds: 'Renews/ends {date}',
  requirePasswordReset: 'Require password reset',
  internalNotes: 'Internal notes',
  supportNote: 'Support note',
  entitlementNeedsNote: 'Paid entitlement needs a support note with at least 12 characters before saving.',
  saveAccount: 'Save account',
  requestReset: 'Request reset',
  resolveRecovery: 'Resolve recovery',
  confirmAccountChange: 'Confirm account change',
  confirmAccountChangeDetail: 'This change affects account access or support state.',
  confirmChange: 'Confirm change',
  confirmDeletion: 'Confirm account deletion state',
  confirmDeletionDetail: 'This marks the account as deleted and blocks normal app access.',
  markDeleted: 'Mark deleted',
  confirmSuspension: 'Confirm account suspension',
  confirmSuspensionDetail: 'This blocks the account from normal Baristachaw access until restored.',
  suspendAccount: 'Suspend account',
  confirmRoleChange: 'Confirm privileged role change',
  confirmRoleChangeDetail: 'Owner and admin role changes affect who can manage users, plans, and launch controls.',
  operatorReview: 'Operator review',
  operatorReason: 'Operator reason',
  required: 'required',
  operatorReasonRequiredPlaceholder: 'Reason for this account access change',
  operatorReasonOptionalPlaceholder: 'Optional note for support history',
  savedToSupportNote: '{count}/220 saved to support note',
  cancel: 'Cancel',
  confirmFeatureDisable: 'Confirm feature disable',
  confirmMaintenanceMode: 'Confirm maintenance mode',
  featureChangeDetail: 'This changes availability for Baristachaw surfaces and should include a clear operator message.',
  cancelFeatureChange: 'Cancel feature flag change',
  userImpact: 'User impact',
  userImpactDetail: 'Users on selected surfaces may see a blocked or degraded feature state until the flag returns to available.',
  operatorMessageRequired: 'Operator message required',
  maintenanceMessagePlaceholder: 'Short user-facing maintenance or disable reason',
  savedToMaintenanceMessage: '{count}/240 saved to maintenance message',
  disableFeature: 'Disable feature',
  applyMaintenance: 'Apply maintenance',
  paymentReadiness: 'Payment readiness',
  active: 'active',
  pastDue: 'past due',
  connectedProviders: 'Connected providers',
  notConfigured: 'not configured',
  marketsPrepared: 'Markets prepared: {markets}.',
  realtimeContract: 'Realtime contract',
  planCatalog: 'Plan catalog',
  planCatalogSubtitle: 'Commercial tiers, quota ceilings, provider mapping, entitlement IDs, and launch billing readiness.',
  reset: 'Reset',
  save: 'Save',
  name: 'Name',
  displayPrice: 'Display price',
  description: 'Description',
  priceUsd: 'Price USD',
  aiDay: 'AI/day',
  deepDay: 'Deep/day',
  scansDay: 'Scans/day',
  storageMb: 'Storage MB',
  seats: 'Seats',
  slaHours: 'SLA hours',
  checkout: 'Checkout',
  productId: 'Product ID',
  priceId: 'Price ID',
  entitlementId: 'Entitlement ID',
  features: 'Features',
  paymentMethods: 'Payment methods',
  recommended: 'Recommended',
  pendingChanges: '{count} pending changes',
  noPendingChanges: 'No pending changes',
  operatorNote: 'Operator note',
  operatorNotePlaceholder: 'Operator reason for audit trail',
  numericFieldsInvalid: 'Numeric fields must be valid numbers.',
  maintenanceControls: 'Maintenance controls',
  maintenanceControlsSubtitle: 'Feature availability flags consumed by web, PWA, and Android parity sessions.',
  userFacingMaintenanceMessage: 'User-facing maintenance message',
  savingMaintenanceControl: 'Saving maintenance control...',
  databaseReadiness: 'Database readiness',
  databaseReadinessSubtitle: 'Persistence, RLS, audit, and plan controls for production operations.',
  catalogOperations: 'Catalog operations',
  catalogOperationsSubtitle: 'Water, dripper, and grinder review queue.',
  queuedCount: '{count} queued',
  needsSourceCount: '{count} needs source',
  approvedCount: '{count} approved',
  noCatalogRequests: 'No catalog requests yet.',
  newCatalogRequest: 'New catalog request',
  queue: 'Queue',
  kind: 'Kind',
  title: 'Title',
  entityId: 'Entity ID',
  sourceUrl: 'Source URL',
  payloadJson: 'Payload JSON',
  payloadMustObject: 'Payload must be a JSON object.',
  payloadInvalid: 'Payload JSON is invalid.',
  auditTrail: 'Audit trail',
  auditTrailSubtitle: 'Latest admin mutations and operational events.',
  launchGate: 'Launch gate',
  launchGateSubtitle: 'The one-week Play Store launch readiness list.',
  usersCopied: '{label} copied',
  copyFailed: 'Copy failed',
  usersCsvExported: 'Users CSV exported',
  auditCsvExported: 'Audit CSV exported',
  exportUnavailable: 'Export unavailable',
  launchHandoff: 'Launch handoff',
  adminChangesSaved: 'Admin changes saved',
  adminChangesFailed: 'Admin changes failed',
  maintenanceSaved: 'Maintenance control saved',
  maintenanceFailed: 'Maintenance control failed',
  planSaved: 'Plan catalog saved',
  planFailed: 'Plan catalog failed to save',
  catalogSaved: 'Catalog request saved',
  catalogFailed: 'Catalog request failed',
  aiDeepScanLimits: '{ai} AI / {deep} deep / {scans} scans daily',
  planLimitsPending: 'plan limits pending',
  customPrice: 'Custom',
  usersLabel: 'users',
} as const;

export type AdminCopyKey = keyof typeof EN_ADMIN_COPY;

const ID_ADMIN_COPY: Record<AdminCopyKey, string> = {
  accessRequiredTitle: 'Akses admin diperlukan',
  accessRequiredAuth: 'Masuk dengan akun owner untuk membuka konsol manajemen.',
  accessRequiredForbidden: 'Akun saat ini belum terdaftar di ADMIN_EMAILS atau ADMIN_USER_IDS.',
  adminRequestFailed: 'Permintaan admin gagal',
  signIn: 'Masuk',
  retry: 'Coba lagi',
  dismissAdminError: 'Tutup error admin',
  pageTitle: 'Manajemen Admin',
  pageSubtitle: 'Kelola user, plan, database, audit, dan kontrol launching.',
  backToApp: 'Aplikasi',
  backToAppTitle: 'Kembali ke aplikasi',
  switchToLight: 'Ubah admin ke mode terang',
  switchToDark: 'Ubah admin ke mode gelap',
  light: 'Terang',
  dark: 'Gelap',
  refresh: 'Muat ulang',
  live: 'Live',
  tabOverview: 'Komando',
  tabUsers: 'User',
  tabPlans: 'Plan',
  tabMaintenance: 'Maintenance',
  tabDatabase: 'Database',
  tabAudit: 'Audit',
  tabLaunch: 'Launching',
  metricTotalUsers: 'Total User',
  metricPaidUsers: 'User Berbayar',
  metricAiToday: 'AI Hari Ini',
  metricLaunchGate: 'Gate Launching',
  activeAccounts: '{count} akun aktif',
  planConversion: '{count}% konversi plan',
  deepRequests: '{count} request deep',
  criticalWarnings: 'Gagal kritis / peringatan',
  exportTitle: 'Paket export operator',
  exportSubtitle: 'Unduh daftar akun, audit trail, atau salin ringkasan handoff launching untuk support dan founder.',
  usersCsv: 'CSV User',
  auditCsv: 'CSV Audit',
  copyHandoff: 'Salin handoff',
  snapshot: 'Snapshot',
  freshness: 'Kesegaran',
  queues: 'Antrean',
  flags: 'Flag',
  queueRisk: 'Antrean risiko',
  queueRecovery: 'Antrean recovery',
  queueBilling: 'Perhatian billing',
  queuePaid: 'User berbayar',
  queueSample: 'Data preview',
  queueAll: 'Semua antrean',
  commandCenterTitle: 'Pusat komando operasional',
  commandCenterSubtitle: 'Antrean prioritas untuk support akun, blocker launching, dan respons maintenance live.',
  riskCardTitle: 'Antrean risiko',
  riskCardDetail: '{count} past-due plus akun suspended atau berisiko tinggi.',
  recoveryCardTitle: 'Recovery',
  recoveryCardDetail: 'Reset password dan permintaan pemulihan akun.',
  billingCardTitle: 'Billing',
  billingCardDetail: 'Review pembayaran, refund, expired, dan past-due.',
  flagsCardTitle: 'Flag',
  flagsCardDetail: 'Kontrol maintenance aktif untuk web, PWA, mobile, atau admin.',
  paidCardTitle: 'Berbayar',
  paidCardDetail: 'Akun Starter, Pro, Team, dan Enterprise.',
  handoffTitle: 'Handoff operator',
  noUrgentHandoff: 'Tidak ada handoff mendesak',
  queuesClear: 'Antrean risiko dan recovery bersih.',
  productionChecks: 'Pemeriksaan production',
  productionChecksSubtitle: 'Kesiapan backend, database, billing, dan AI saat ini.',
  planMix: 'Komposisi plan',
  recommendations: 'Rekomendasi',
  usersSearchPlaceholder: 'Cari nama, username, email, atau user id',
  allStatus: 'Semua status',
  allPlans: 'Semua plan',
  allRecovery: 'Semua recovery',
  noMatchingUsers: 'Tidak ada user cocok',
  noMatchingUsersSubtitle: 'Sesuaikan pencarian, status, atau filter plan.',
  account: 'Akun',
  status: 'Status',
  plan: 'Plan',
  billing: 'Billing',
  role: 'Role',
  recovery: 'Recovery',
  usageToday: 'Pemakaian hari ini',
  risk: 'Risiko',
  lastSeen: 'Terakhir aktif',
  manage: 'Kelola',
  preview: 'preview',
  unassigned: 'belum diisi',
  unknown: 'Tidak diketahui',
  localeNA: 'locale belum ada',
  actionRequired: 'Butuh tindakan',
  passwordResetRequired: 'Reset password wajib',
  saving: 'Menyimpan...',
  savingAccount: 'Menyimpan akun...',
  accountControl: 'Kontrol akun',
  closeAccountPanel: 'Tutup panel akun',
  created: 'Dibuat',
  currentPlan: 'Plan saat ini',
  displayName: 'Nama tampil',
  username: 'Username',
  adminQuickActions: 'Aksi cepat admin',
  adminQuickActionsSubtitle: 'Gunakan untuk flow support launching yang sering dipakai tanpa mencari setiap field.',
  restoreActive: 'Pulihkan aktif',
  suspendReview: 'Suspend untuk review',
  planQuickControl: 'Kontrol plan cepat',
  planQuickControlSubtitle: 'Pilih tier, lihat kuota, lalu terapkan entitlement dengan catatan support siap audit.',
  provider: 'Provider',
  market: 'Market',
  manualReview: 'review manual',
  selected: 'dipilih',
  applyProvisional: 'Terapkan sementara',
  applyFree: 'Terapkan gratis',
  billingEntitlement: 'Billing dan entitlement',
  receiptModeDetail: 'Mode receipt menerapkan {limit} langsung, lalu tetap meminta review manual sampai langganan diverifikasi.',
  billingStatus: 'Status billing',
  paymentActionRequired: 'Tindakan pembayaran wajib',
  receiptReceived: 'Receipt diterima',
  markPaid: 'Tandai paid',
  markPastDue: 'Tandai past due',
  customer: 'Customer',
  subscription: 'Subscription',
  renewsEnds: 'Perpanjang/berakhir {date}',
  requirePasswordReset: 'Wajibkan reset password',
  internalNotes: 'Catatan internal',
  supportNote: 'Catatan support',
  entitlementNeedsNote: 'Entitlement berbayar butuh catatan support minimal 12 karakter sebelum disimpan.',
  saveAccount: 'Simpan akun',
  requestReset: 'Minta reset',
  resolveRecovery: 'Selesaikan recovery',
  confirmAccountChange: 'Konfirmasi perubahan akun',
  confirmAccountChangeDetail: 'Perubahan ini memengaruhi akses akun atau status support.',
  confirmChange: 'Konfirmasi perubahan',
  confirmDeletion: 'Konfirmasi status akun dihapus',
  confirmDeletionDetail: 'Ini menandai akun sebagai dihapus dan memblokir akses aplikasi normal.',
  markDeleted: 'Tandai dihapus',
  confirmSuspension: 'Konfirmasi suspend akun',
  confirmSuspensionDetail: 'Ini memblokir akses Baristachaw normal sampai dipulihkan.',
  suspendAccount: 'Suspend akun',
  confirmRoleChange: 'Konfirmasi perubahan role penting',
  confirmRoleChangeDetail: 'Role owner dan admin memengaruhi siapa yang bisa mengelola user, plan, dan kontrol launching.',
  operatorReview: 'Review operator',
  operatorReason: 'Alasan operator',
  required: 'wajib',
  operatorReasonRequiredPlaceholder: 'Alasan perubahan akses akun ini',
  operatorReasonOptionalPlaceholder: 'Catatan opsional untuk riwayat support',
  savedToSupportNote: '{count}/220 tersimpan ke catatan support',
  cancel: 'Batal',
  confirmFeatureDisable: 'Konfirmasi fitur dinonaktifkan',
  confirmMaintenanceMode: 'Konfirmasi mode maintenance',
  featureChangeDetail: 'Perubahan ini mengatur ketersediaan permukaan Baristachaw dan harus punya pesan operator yang jelas.',
  cancelFeatureChange: 'Batalkan perubahan feature flag',
  userImpact: 'Dampak user',
  userImpactDetail: 'User di permukaan terpilih bisa melihat fitur diblokir atau terdegradasi sampai flag kembali tersedia.',
  operatorMessageRequired: 'Pesan operator wajib',
  maintenanceMessagePlaceholder: 'Alasan maintenance atau disable yang terlihat oleh user',
  savedToMaintenanceMessage: '{count}/240 tersimpan ke pesan maintenance',
  disableFeature: 'Nonaktifkan fitur',
  applyMaintenance: 'Terapkan maintenance',
  paymentReadiness: 'Kesiapan pembayaran',
  active: 'aktif',
  pastDue: 'past due',
  connectedProviders: 'Provider terhubung',
  notConfigured: 'belum dikonfigurasi',
  marketsPrepared: 'Market siap: {markets}.',
  realtimeContract: 'Kontrak realtime',
  planCatalog: 'Katalog plan',
  planCatalogSubtitle: 'Tier komersial, batas kuota, mapping provider, entitlement ID, dan kesiapan billing launching.',
  reset: 'Reset',
  save: 'Simpan',
  name: 'Nama',
  displayPrice: 'Harga tampil',
  description: 'Deskripsi',
  priceUsd: 'Harga USD',
  aiDay: 'AI/hari',
  deepDay: 'Deep/hari',
  scansDay: 'Scan/hari',
  storageMb: 'Storage MB',
  seats: 'Seat',
  slaHours: 'Jam SLA',
  checkout: 'Checkout',
  productId: 'Product ID',
  priceId: 'Price ID',
  entitlementId: 'Entitlement ID',
  features: 'Fitur',
  paymentMethods: 'Metode pembayaran',
  recommended: 'Direkomendasikan',
  pendingChanges: '{count} perubahan menunggu',
  noPendingChanges: 'Tidak ada perubahan',
  operatorNote: 'Catatan operator',
  operatorNotePlaceholder: 'Alasan operator untuk audit trail',
  numericFieldsInvalid: 'Field angka harus valid.',
  maintenanceControls: 'Kontrol maintenance',
  maintenanceControlsSubtitle: 'Feature availability flag yang dipakai web, PWA, dan sesi Android parity.',
  userFacingMaintenanceMessage: 'Pesan maintenance untuk user',
  savingMaintenanceControl: 'Menyimpan kontrol maintenance...',
  databaseReadiness: 'Kesiapan database',
  databaseReadinessSubtitle: 'Persistence, RLS, audit, dan kontrol plan untuk operasi production.',
  catalogOperations: 'Operasi katalog',
  catalogOperationsSubtitle: 'Antrean review water, dripper, dan grinder.',
  queuedCount: '{count} antre',
  needsSourceCount: '{count} butuh sumber',
  approvedCount: '{count} disetujui',
  noCatalogRequests: 'Belum ada request katalog.',
  newCatalogRequest: 'Request katalog baru',
  queue: 'Antrekan',
  kind: 'Jenis',
  title: 'Judul',
  entityId: 'Entity ID',
  sourceUrl: 'Source URL',
  payloadJson: 'Payload JSON',
  payloadMustObject: 'Payload harus berupa object JSON.',
  payloadInvalid: 'Payload JSON tidak valid.',
  auditTrail: 'Audit trail',
  auditTrailSubtitle: 'Mutasi admin dan event operasional terbaru.',
  launchGate: 'Gate launching',
  launchGateSubtitle: 'Daftar kesiapan launching Play Store satu minggu.',
  usersCopied: '{label} tersalin',
  copyFailed: 'Gagal menyalin',
  usersCsvExported: 'CSV user berhasil diexport',
  auditCsvExported: 'CSV audit berhasil diexport',
  exportUnavailable: 'Export tidak tersedia',
  launchHandoff: 'Handoff launching',
  adminChangesSaved: 'Perubahan admin tersimpan',
  adminChangesFailed: 'Perubahan admin gagal',
  maintenanceSaved: 'Kontrol maintenance tersimpan',
  maintenanceFailed: 'Kontrol maintenance gagal',
  planSaved: 'Katalog plan tersimpan',
  planFailed: 'Katalog plan gagal disimpan',
  catalogSaved: 'Request katalog tersimpan',
  catalogFailed: 'Request katalog gagal',
  aiDeepScanLimits: '{ai} AI / {deep} deep / {scans} scan per hari',
  planLimitsPending: 'limit plan belum siap',
  customPrice: 'Custom',
  usersLabel: 'user',
};

const PARTIAL_ADMIN_COPY: Partial<Record<Language, Partial<Record<AdminCopyKey, string>>>> = {
  ar: {
    pageTitle: 'إدارة المشرف',
    pageSubtitle: 'إدارة المستخدمين والخطط وقاعدة البيانات والتدقيق والإطلاق.',
    tabOverview: 'التحكم',
    tabUsers: 'المستخدمون',
    tabPlans: 'الخطط',
    tabMaintenance: 'الصيانة',
    tabDatabase: 'قاعدة البيانات',
    tabAudit: 'التدقيق',
    tabLaunch: 'الإطلاق',
    manage: 'إدارة',
    accountControl: 'التحكم بالحساب',
    planCatalog: 'كتالوج الخطط',
    operatorNote: 'ملاحظة المشغل',
    catalogOperations: 'عمليات الكتالوج',
    newCatalogRequest: 'طلب كتالوج جديد',
    payloadJson: 'Payload JSON',
    save: 'حفظ',
    queue: 'إضافة للانتظار',
    refresh: 'تحديث',
    light: 'فاتح',
    dark: 'داكن',
  },
  zh: {
    pageTitle: '管理员管理',
    pageSubtitle: '管理用户、套餐、数据库、审计和发布控制。',
    tabOverview: '指挥台',
    tabUsers: '用户',
    tabPlans: '套餐',
    tabMaintenance: '维护',
    tabDatabase: '数据库',
    tabAudit: '审计',
    tabLaunch: '发布',
    manage: '管理',
    accountControl: '账户控制',
    planCatalog: '套餐目录',
    operatorNote: '操作员备注',
    catalogOperations: '目录操作',
    newCatalogRequest: '新目录请求',
    save: '保存',
    queue: '加入队列',
    refresh: '刷新',
  },
  ja: {
    pageTitle: '管理コンソール',
    pageSubtitle: 'ユーザー、プラン、データベース、監査、ローンチ管理。',
    tabOverview: 'コマンド',
    tabUsers: 'ユーザー',
    tabPlans: 'プラン',
    tabMaintenance: 'メンテナンス',
    tabDatabase: 'データベース',
    tabAudit: '監査',
    tabLaunch: 'ローンチ',
    manage: '管理',
    accountControl: 'アカウント管理',
    planCatalog: 'プランカタログ',
    operatorNote: 'オペレーターメモ',
    catalogOperations: 'カタログ操作',
    newCatalogRequest: '新規カタログ申請',
    save: '保存',
    queue: 'キューへ追加',
    refresh: '更新',
  },
  ko: {
    pageTitle: '관리자 관리',
    pageSubtitle: '사용자, 플랜, 데이터베이스, 감사, 출시 제어를 관리합니다.',
    tabOverview: '지휘',
    tabUsers: '사용자',
    tabPlans: '플랜',
    tabMaintenance: '점검',
    tabDatabase: '데이터베이스',
    tabAudit: '감사',
    tabLaunch: '출시',
    manage: '관리',
    accountControl: '계정 제어',
    planCatalog: '플랜 카탈로그',
    operatorNote: '운영자 메모',
    catalogOperations: '카탈로그 작업',
    newCatalogRequest: '새 카탈로그 요청',
    save: '저장',
    queue: '대기열 추가',
    refresh: '새로고침',
  },
  th: {
    pageTitle: 'จัดการผู้ดูแล',
    pageSubtitle: 'จัดการผู้ใช้ แผน ฐานข้อมูล การตรวจสอบ และการเปิดตัว',
    tabOverview: 'ศูนย์ควบคุม',
    tabUsers: 'ผู้ใช้',
    tabPlans: 'แผน',
    tabMaintenance: 'บำรุงรักษา',
    tabDatabase: 'ฐานข้อมูล',
    tabAudit: 'ตรวจสอบ',
    tabLaunch: 'เปิดตัว',
    manage: 'จัดการ',
    accountControl: 'ควบคุมบัญชี',
    planCatalog: 'แคตตาล็อกแผน',
    operatorNote: 'บันทึกผู้ดูแล',
    catalogOperations: 'งานแคตตาล็อก',
    newCatalogRequest: 'คำขอแคตตาล็อกใหม่',
    save: 'บันทึก',
    queue: 'เข้าคิว',
    refresh: 'รีเฟรช',
  },
  vi: {
    pageTitle: 'Quản lý Admin',
    pageSubtitle: 'Quản lý người dùng, gói, cơ sở dữ liệu, kiểm toán và phát hành.',
    tabOverview: 'Điều phối',
    tabUsers: 'Người dùng',
    tabPlans: 'Gói',
    tabMaintenance: 'Bảo trì',
    tabDatabase: 'Cơ sở dữ liệu',
    tabAudit: 'Kiểm toán',
    tabLaunch: 'Phát hành',
    manage: 'Quản lý',
    accountControl: 'Điều khiển tài khoản',
    planCatalog: 'Danh mục gói',
    operatorNote: 'Ghi chú vận hành',
    catalogOperations: 'Vận hành danh mục',
    newCatalogRequest: 'Yêu cầu danh mục mới',
    save: 'Lưu',
    queue: 'Xếp hàng',
    refresh: 'Làm mới',
  },
  ms: {
    pageTitle: 'Pengurusan Admin',
    pageSubtitle: 'Urus pengguna, pelan, pangkalan data, audit, dan kawalan pelancaran.',
    tabOverview: 'Komando',
    tabUsers: 'Pengguna',
    tabPlans: 'Pelan',
    tabMaintenance: 'Penyelenggaraan',
    tabDatabase: 'Pangkalan data',
    tabAudit: 'Audit',
    tabLaunch: 'Pelancaran',
    manage: 'Urus',
    accountControl: 'Kawalan akaun',
    planCatalog: 'Katalog pelan',
    operatorNote: 'Nota operator',
    catalogOperations: 'Operasi katalog',
    newCatalogRequest: 'Permintaan katalog baharu',
    save: 'Simpan',
    queue: 'Masuk giliran',
    refresh: 'Segar semula',
  },
};

const EN_ENUM_LABELS: Record<string, string> = {
  pass: 'Pass',
  warn: 'Warning',
  fail: 'Fail',
  active: 'Active',
  trialing: 'Trialing',
  past_due: 'Past due',
  suspended: 'Suspended',
  deleted: 'Deleted',
  none: 'None',
  requested: 'Requested',
  verified: 'Verified',
  resolved: 'Resolved',
  rejected: 'Rejected',
  cancelled: 'Cancelled',
  expired: 'Expired',
  refunded: 'Refunded',
  available: 'Available',
  maintenance: 'Maintenance',
  disabled: 'Disabled',
  selected: 'Selected',
  owner: 'Owner',
  admin: 'Admin',
  support: 'Support',
  analyst: 'Analyst',
  user: 'User',
  free: 'Free',
  starter: 'Starter',
  pro: 'Pro',
  team: 'Team',
  enterprise: 'Enterprise',
  manual: 'Manual',
  admin_provider: 'Admin',
  google_play: 'Google Play',
  app_store: 'App Store',
  stripe: 'Stripe',
  revenuecat: 'RevenueCat',
  indonesia: 'Indonesia',
  brunei: 'Brunei',
  global: 'Global',
  unknown: 'Unknown',
  disabled_checkout: 'Disabled',
  external: 'External',
  stripe_checkout: 'Stripe Checkout',
  play_billing: 'Play Billing',
  manual_invoice: 'Manual invoice',
  grinder: 'Grinder',
  water: 'Water',
  dripper: 'Dripper',
  web: 'Web',
  pwa: 'PWA',
  mobile: 'Mobile',
  global_surface: 'Global',
  sample: 'Sample',
  supabase: 'Supabase',
  preview: 'Preview',
  live: 'Live',
};

const ID_ENUM_LABELS: Record<string, string> = {
  pass: 'Lolos',
  warn: 'Peringatan',
  fail: 'Gagal',
  active: 'Aktif',
  trialing: 'Trial',
  past_due: 'Terlambat bayar',
  suspended: 'Suspended',
  deleted: 'Dihapus',
  none: 'Tidak ada',
  requested: 'Diminta',
  verified: 'Terverifikasi',
  resolved: 'Selesai',
  rejected: 'Ditolak',
  cancelled: 'Dibatalkan',
  expired: 'Expired',
  refunded: 'Refunded',
  available: 'Tersedia',
  maintenance: 'Maintenance',
  disabled: 'Nonaktif',
  selected: 'Dipilih',
  owner: 'Owner',
  admin: 'Admin',
  support: 'Support',
  analyst: 'Analis',
  user: 'User',
  free: 'Gratis',
  starter: 'Starter',
  pro: 'Pro',
  team: 'Team',
  enterprise: 'Enterprise',
  manual: 'Manual',
  admin_provider: 'Admin',
  google_play: 'Google Play',
  app_store: 'App Store',
  stripe: 'Stripe',
  revenuecat: 'RevenueCat',
  indonesia: 'Indonesia',
  brunei: 'Brunei',
  global: 'Global',
  unknown: 'Tidak diketahui',
  disabled_checkout: 'Nonaktif',
  external: 'External',
  stripe_checkout: 'Stripe Checkout',
  play_billing: 'Play Billing',
  manual_invoice: 'Invoice manual',
  grinder: 'Grinder',
  water: 'Water',
  dripper: 'Dripper',
  web: 'Web',
  pwa: 'PWA',
  mobile: 'Mobile',
  global_surface: 'Global',
  sample: 'Sample',
  supabase: 'Supabase',
  preview: 'Preview',
  live: 'Live',
};

const PARTIAL_ENUM_LABELS: Partial<Record<Language, Record<string, string>>> = {
  id: ID_ENUM_LABELS,
  ms: {
    pass: 'Lulus',
    warn: 'Amaran',
    fail: 'Gagal',
    active: 'Aktif',
    trialing: 'Percubaan',
    past_due: 'Tertunggak',
    suspended: 'Digantung',
    deleted: 'Dipadam',
    available: 'Tersedia',
    maintenance: 'Penyelenggaraan',
    disabled: 'Dilumpuhkan',
    selected: 'Dipilih',
  },
};

function normalizeLanguage(value?: string | null): Language {
  const short = String(value || '').trim().toLowerCase().split(/[-_]/)[0];
  return isSupportedLanguage(short) ? short : DEFAULT_LANGUAGE;
}

function fallbackLabel(value: string): string {
  return value.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function formatTemplate(template: string, params: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (token, key) => (
    Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : token
  ));
}

export function createAdminCopy(language?: Language | string | null) {
  const normalizedLanguage = normalizeLanguage(language);
  const locale = getLanguageLocale(normalizedLanguage);
  const copy = {
    ...EN_ADMIN_COPY,
    ...(normalizedLanguage === 'id' ? ID_ADMIN_COPY : PARTIAL_ADMIN_COPY[normalizedLanguage]),
  } as Record<AdminCopyKey, string>;
  const enumLabels = {
    ...EN_ENUM_LABELS,
    ...(PARTIAL_ENUM_LABELS[normalizedLanguage] || {}),
  };

  return {
    language: normalizedLanguage,
    locale,
    text(key: AdminCopyKey) {
      return copy[key] || EN_ADMIN_COPY[key] || key;
    },
    format(key: AdminCopyKey, params?: Record<string, string | number>) {
      return formatTemplate(copy[key] || EN_ADMIN_COPY[key] || key, params);
    },
    enumLabel(value: string) {
      const enumKey = value === 'admin' ? 'admin' : value === 'global' ? 'global_surface' : value;
      return enumLabels[enumKey] || fallbackLabel(value);
    },
    number(value: number) {
      return new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(value);
    },
    currencyUsd(value: number) {
      if (value <= 0) return copy.customPrice;
      return new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value);
    },
    date(value: string) {
      const date = new Date(value);
      if (Number.isNaN(date.getTime())) return copy.unknown;
      return new Intl.DateTimeFormat(locale, {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }).format(date);
    },
    raw: copy,
  };
}

export type AdminCopy = ReturnType<typeof createAdminCopy>;
