import { DEFAULT_LANGUAGE, getLanguageLocale, isSupportedLanguage } from '../constants';
import type { Language } from '../types';

const EN_ADMIN_COPY = {
  accessRequiredTitle: 'Admin access required',
  accessRequiredAuth: 'Sign in with an owner account to open the management console.',
  accessRequiredForbidden: 'Your current account is not in ADMIN_EMAILS or ADMIN_USER_IDS.',
  adminRequestFailed: 'Admin request failed',
  signIn: 'Sign in',
  retry: 'Retry',
  dismissAdminError: 'Dismiss admin error',
  pageTitle: 'Admin Management',
  pageSubtitle: 'Users, plans, database readiness, audit, and launch control.',
  skipToAdminContent: 'Skip to admin content',
  adminNavigation: 'Admin navigation',
  adminContent: 'Admin content',
  mobileAdminDock: 'Mobile admin command bar',
  attentionItems: 'attention items',
  backToApp: 'App',
  backToAppTitle: 'Back to application',
  switchToLight: 'Switch admin to light mode',
  switchToDark: 'Switch admin to dark mode',
  light: 'Light',
  dark: 'Dark',
  refresh: 'Refresh',
  live: 'Live',
  livePaused: 'Live paused',
  tabOverview: 'Command',
  tabUsers: 'Users',
  tabPlans: 'Plans',
  tabQueues: 'Queues',
  tabAi: 'AI Control',
  tabMaintenance: 'Maintenance',
  tabDatabase: 'Database',
  tabRecipes: 'Recipe Library',
  tabAudit: 'Audit',
  tabLaunch: 'Launch',
  metricTotalUsers: 'Total Users',
  metricPaidUsers: 'Paid Users',
  metricAiToday: 'AI Today',
  metricLaunchGate: 'Launch Gate',
  activeAccounts: '{count} active accounts',
  planConversion: '{count}% plan conversion',
  deepRequests: '{count} deep requests',
  criticalWarnings: 'Critical failures / warnings',
  exportTitle: 'Operator export deck',
  exportSubtitle: 'Download the current account roster, audit trail, or copy a launch handoff summary for support and founders.',
  usersCsv: 'Users CSV',
  auditCsv: 'Audit CSV',
  copyHandoff: 'Copy handoff',
  snapshot: 'Snapshot',
  freshness: 'Freshness',
  queues: 'Queues',
  flags: 'Flags',
  queueRisk: 'Risk queue',
  queueRecovery: 'Recovery queue',
  queueBilling: 'Billing attention',
  queuePaid: 'Paid users',
  queueSample: 'Preview data',
  queueAll: 'All queues',
  paymentQueuesTitle: 'Payment and plan queues',
  paymentQueuesSubtitle: 'Review manual invoices, proof uploads, pending entitlements, and billing attention users from one compact queue.',
  paymentQueueSearchLabel: 'Search payment queue',
  paymentQueueSearchPlaceholder: 'Search invoice, email, user, plan, bank, proof path',
  paymentQueueResults: '{shown} of {total} payment requests shown',
  paymentQueueEmpty: 'No manual payment requests match this queue.',
  paymentQueueAll: 'All',
  paymentQueuePending: 'Pending',
  paymentQueueReceipt: 'Proof received',
  paymentQueueVerified: 'Verified',
  paymentQueueRejected: 'Rejected',
  paymentQueueExpired: 'Expired',
  paymentQueueBuyer: 'Buyer',
  paymentQueueTransfer: 'Transfer',
  paymentQueueProof: 'Proof',
  paymentQueueActions: 'Verify only after amount, account, and proof are checked.',
  paymentQueueOpenProof: 'View proof',
  paymentQueueOpenUser: 'Open user',
  paymentQueuePlanUsers: 'Plan and billing attention users',
  paymentQueuePlanUsersSubtitle: 'Users whose entitlement, renewal, past-due, or manual payment state needs admin review.',
  paymentQueueNoBillingUsers: 'No billing attention users right now.',
  paymentQueueKpiManual: 'Open manual',
  paymentQueueKpiProof: 'Proof queue',
  paymentQueueKpiPlan: 'Plan users',
  paymentQueueKpiClosed: 'Closed review',
  commandCenterTitle: 'Operations command center',
  commandCenterSubtitle: 'Prioritized queues for account support, launch blockers, and live maintenance response.',
  riskCardTitle: 'Risk queue',
  riskCardDetail: '{count} past-due plus suspended or high-risk accounts.',
  recoveryCardTitle: 'Recovery',
  recoveryCardDetail: 'Password reset and account recovery requests.',
  billingCardTitle: 'Billing',
  billingCardDetail: 'Payment action, refund, expired, and past-due reviews.',
  flagsCardTitle: 'Flags',
  flagsCardDetail: 'Active web, PWA, mobile, or admin maintenance controls.',
  paidCardTitle: 'Paid',
  paidCardDetail: 'Starter, Pro, Team, and Enterprise accounts.',
  handoffTitle: 'Operator handoff',
  noUrgentHandoff: 'No urgent handoff',
  queuesClear: 'Risk and recovery queues are clear.',
  productionChecks: 'Production checks',
  productionChecksSubtitle: 'Current backend, database, billing, and AI readiness.',
  planMix: 'Plan mix',
  recommendations: 'Recommendations',
  userFilters: 'User filters',
  usersSearchLabel: 'Search users',
  clearSearch: 'Clear search',
  clearFilters: 'Clear filters',
  queueFilterLabel: 'Queue filter',
  statusFilterLabel: 'Status filter',
  planFilterLabel: 'Plan filter',
  recoveryFilterLabel: 'Recovery filter',
  userResultsSummary: '{shown} of {total} users shown',
  selectedUserSummary: 'Selected: {name}',
  selectUserHint: 'Select a user to open account controls.',
  userCardControls: 'User card controls',
  usersTableCaption: 'User management table with account, plan, billing, role, recovery, usage, risk, and last seen controls.',
  usersSearchPlaceholder: 'Search name, username, email, or user id',
  allStatus: 'All status',
  allPlans: 'All plans',
  allRecovery: 'All recovery',
  noMatchingUsers: 'No matching users',
  noMatchingUsersSubtitle: 'Adjust search, status, or plan filters.',
  account: 'Account',
  status: 'Status',
  plan: 'Plan',
  billing: 'Billing',
  role: 'Role',
  recovery: 'Recovery',
  usageToday: 'Usage today',
  risk: 'Risk',
  lastSeen: 'Last seen',
  manage: 'Manage',
  preview: 'preview',
  unassigned: 'unassigned',
  unknown: 'Unknown',
  localeNA: 'locale n/a',
  actionRequired: 'Action required',
  passwordResetRequired: 'Password reset required',
  saving: 'Saving...',
  savingAccount: 'Saving account...',
  accountControl: 'Account control',
  closeAccountPanel: 'Close account panel',
  created: 'Created',
  currentPlan: 'Current plan',
  displayName: 'Display name',
  username: 'Username',
  adminQuickActions: 'Admin quick actions',
  adminQuickActionsSubtitle: 'Use these for the common launch-support flows without hunting through every field.',
  restoreActive: 'Restore active',
  suspendReview: 'Suspend review',
  planQuickControl: 'Plan quick control',
  planQuickControlSubtitle: 'Pick a tier, see the quota, then apply entitlement with a review-ready support note.',
  provider: 'Provider',
  market: 'Market',
  manualReview: 'manual review',
  selected: 'selected',
  applyProvisional: 'Apply provisional',
  applyFree: 'Apply free',
  billingEntitlement: 'Billing and entitlement',
  receiptModeDetail: 'Receipt mode applies {limit} immediately, then keeps manual review required until the subscription is verified.',
  billingStatus: 'Billing status',
  paymentActionRequired: 'Payment action required',
  receiptReceived: 'Receipt received',
  markPaid: 'Mark paid',
  markPastDue: 'Mark past due',
  billingPeriodStart: 'Billing start',
  billingPeriodEnd: 'Billing end',
  pastDueDate: 'Past due date',
  contactUserWhatsApp: 'Contact user',
  paymentSupportWhatsApp: 'Payment support',
  whatsapp: 'WhatsApp',
  customer: 'Customer',
  subscription: 'Subscription',
  renewsEnds: 'Renews/ends {date}',
  requirePasswordReset: 'Require password reset',
  internalNotes: 'Internal notes',
  supportNote: 'Support note',
  entitlementNeedsNote: 'Paid entitlement needs a support note with at least 12 characters before saving.',
  saveAccount: 'Save account',
  requestReset: 'Request reset',
  resolveRecovery: 'Resolve recovery',
  confirmAccountChange: 'Confirm account change',
  confirmAccountChangeDetail: 'This change affects account access or support state.',
  confirmChange: 'Confirm change',
  confirmDeletion: 'Confirm account deletion state',
  confirmDeletionDetail: 'This marks the account as deleted and blocks normal app access.',
  markDeleted: 'Mark deleted',
  confirmSuspension: 'Confirm account suspension',
  confirmSuspensionDetail: 'This blocks the account from normal Baristachaw access until restored.',
  suspendAccount: 'Suspend account',
  confirmRoleChange: 'Confirm privileged role change',
  confirmRoleChangeDetail: 'Owner and admin role changes affect who can manage users, plans, and launch controls.',
  operatorReview: 'Operator review',
  operatorReason: 'Operator reason',
  required: 'required',
  operatorReasonRequiredPlaceholder: 'Reason for this account access change',
  operatorReasonOptionalPlaceholder: 'Optional note for support history',
  savedToSupportNote: '{count}/220 saved to support note',
  cancel: 'Cancel',
  confirmFeatureDisable: 'Confirm feature disable',
  confirmMaintenanceMode: 'Confirm maintenance mode',
  featureChangeDetail: 'This changes availability for Baristachaw surfaces and should include a clear operator message.',
  cancelFeatureChange: 'Cancel feature flag change',
  userImpact: 'User impact',
  userImpactDetail: 'Users on selected surfaces may see a blocked or degraded feature state until the flag returns to available.',
  operatorMessageRequired: 'Operator message required',
  maintenanceMessagePlaceholder: 'Short user-facing maintenance or disable reason',
  savedToMaintenanceMessage: '{count}/240 saved to maintenance message',
  disableFeature: 'Disable feature',
  applyMaintenance: 'Apply maintenance',
  paymentReadiness: 'Payment readiness',
  active: 'active',
  pastDue: 'past due',
  connectedProviders: 'Connected providers',
  notConfigured: 'not configured',
  marketsPrepared: 'Markets prepared: {markets}.',
  realtimeContract: 'Realtime contract',
  planCatalog: 'Plan catalog',
  planCatalogSubtitle: 'Commercial tiers, quota ceilings, provider mapping, entitlement IDs, and launch billing readiness.',
  reset: 'Reset',
  save: 'Save',
  name: 'Name',
  displayPrice: 'Display price',
  description: 'Description',
  priceUsd: 'Price USD',
  aiDay: 'AI/day',
  deepDay: 'Deep/day',
  scansDay: 'AI Scanner Limit/day',
  storageMb: 'Storage MB',
  seats: 'Seats',
  slaHours: 'SLA hours',
  checkout: 'Checkout',
  productId: 'Product ID',
  priceId: 'Price ID',
  entitlementId: 'Entitlement ID',
  features: 'Features',
  paymentMethods: 'Payment methods',
  recommended: 'Recommended',
  pendingChanges: '{count} pending changes',
  noPendingChanges: 'No pending changes',
  operatorNote: 'Operator note',
  operatorNotePlaceholder: 'Operator reason for audit trail',
  numericFieldsInvalid: 'Numbers must stay within safe plan limits: price/quotas cannot be negative, seats and SLA must be at least 1.',
  pricingOperations: 'Pricing operations',
  pricingOperationsSubtitle: 'Manage dynamic plan prices and promo codes used by billing checkout.',
  dynamicPricing: 'Dynamic pricing',
  dynamicPricingSubtitle: 'Active rows override static catalog prices for plan cards and checkout.',
  promoCodes: 'Promo codes',
  promoCodesSubtitle: 'Voucher rules are validated server-side before checkout discounts apply.',
  addPrice: 'Add price',
  addPromo: 'Add promo',
  edit: 'Edit',
  delete: 'Delete',
  duration: 'Duration',
  currency: 'Currency',
  originalPrice: 'Original price',
  discountPrice: 'Discount price',
  inactive: 'inactive',
  savePrice: 'Save price',
  savePromo: 'Save promo',
  promoCode: 'Promo code',
  discountType: 'Discount type',
  discountValue: 'Discount value',
  maxUses: 'Max uses',
  validUntil: 'Valid until',
  validPlanCodes: 'Valid plans',
  validDurations: 'Valid durations',
  percentageDiscount: 'Percentage',
  fixedAmountDiscount: 'Fixed amount',
  discount: 'Discount',
  currentUses: 'Uses',
  exhausted: 'exhausted',
  activePricesEmpty: 'No active custom prices yet. Static catalog prices remain in use.',
  promosEmpty: 'No promo codes configured.',
  operatorNoteRequired: 'Operator note must be at least 12 characters.',
  priceValidationRequired: 'Plan, duration, currency, and original price are required.',
  promoValidationRequired: 'Promo code, discount type, and discount value are required.',
  deletePriceTitle: 'Delete plan price',
  deletePromoTitle: 'Delete promo code',
  deletePriceDescription: 'Delete {item}? Checkout will fall back to the static catalog price.',
  deletePromoDescription: 'Delete {item}? This promo code will stop working for checkout.',
  confirmDelete: 'Delete',
  maintenanceControls: 'Maintenance controls',
  maintenanceControlsSubtitle: 'Feature availability flags consumed by web, PWA, and Android parity sessions.',
  aiProviderControls: 'AI provider control',
  aiProviderControlsSubtitle: 'Server-only provider health, key pool readiness, fallback priority, and admin on/off controls without exposing API keys.',
  aiProviderSecurityNote: 'API key values are never sent to the browser. Admin only sees counts, status, model, and sanitized error codes.',
  aiProviderReady: 'AI chain ready',
  aiEnabledProviders: 'Enabled providers',
  aiConfiguredProviders: 'Configured providers',
  aiPaidCreditProviders: 'Paid credit pools',
  aiStandardKeys: 'Standard keys',
  aiPaidKeys: 'Paid keys',
  aiPrimaryModel: 'Primary model',
  aiRecommendedFor: 'Used for',
  aiLastHealth: 'Last health',
  aiNoKeys: 'No server keys configured',
  aiFallbackPolicy: 'Admin-controlled fallback chain',
  aiNoSecretLeak: 'Secret-safe inventory',
  aiBrewUsageTitle: 'AI Brew provider usage',
  aiBrewUsageSubtitle: 'Tracks the online AI provider/model actually used by AI Brew, not local planner fallback or button clicks.',
  aiBrewFallbackTitle: 'AI Brew fallback rate',
  aiBrewFallbackSubtitle: 'Counts optimizer rejected/no-change and sequence fallback events reported by production clients.',
  aiBrewFallbackRate: 'Fallback rate',
  aiBrewFallbackOptimizerRejected: 'Optimizer rejected',
  aiBrewFallbackNoChange: 'No-change kept',
  aiBrewFallbackSequence: 'Sequence fallback',
  aiBrewFallbackRecent: 'Recent fallback events',
  aiBrewFallbackNoEvents: 'No AI Brew fallback events recorded yet.',
  aiBrewFallbackThreshold: 'Alert threshold',
  aiBrewFallbackTrend: '7-day trend',
  aiUsageToday: 'Today',
  aiUsageMonth: 'This month',
  aiUsageCustom: 'Custom range',
  aiUsageTokens: 'Tokens',
  aiUsageCost: 'Cost estimate',
  aiUsageFailures: 'Failures',
  aiUsageLatency: 'Avg latency',
  aiUsageEstimated: 'Estimated',
  aiUsageFrom: 'From',
  aiUsageTo: 'To',
  aiUsageApply: 'Apply range',
  aiUsageProviderBreakdown: 'Provider usage this month',
  aiUsageRecentEvents: 'Recent AI Brew calls',
  aiUsageNoEvents: 'No online AI Brew calls recorded yet.',
  userFacingMaintenanceMessage: 'User-facing maintenance message',
  savingMaintenanceControl: 'Saving maintenance control...',
  databaseReadiness: 'Database readiness',
  databaseReadinessSubtitle: 'Persistence, RLS, audit, and plan controls for production operations.',
  catalogOperations: 'Catalog operations',
  catalogOperationsSubtitle: 'Water, dripper, and grinder review queue.',
  recipeLibrary: 'Recipe Library',
  recipeLibrarySubtitle: 'Saved AI Brew plans, Collection recipes, and taste feedback synced from logged-in users.',
  recipeLibrarySynced: 'Synced items',
  recipeLibraryAiBrew: 'AI Brew plans',
  recipeLibraryCollection: 'Collection recipes',
  recipeLibraryFeedback: 'Taste feedback',
  recipeLibraryRecent: 'Recent saved recipes',
  recipeLibraryNoItems: 'No synced recipes yet.',
  recipeLibraryGap: 'Recipe sync gap',
  recipeLibraryReady: 'Recipe library ready',
  queuedCount: '{count} queued',
  needsSourceCount: '{count} needs source',
  approvedCount: '{count} approved',
  noCatalogRequests: 'No catalog requests yet.',
  newCatalogRequest: 'New catalog request',
  queue: 'Queue',
  kind: 'Kind',
  title: 'Title',
  entityId: 'Entity ID',
  sourceUrl: 'Source URL',
  payloadJson: 'Payload JSON',
  payloadMustObject: 'Payload must be a JSON object.',
  payloadInvalid: 'Payload JSON is invalid.',
  auditTrail: 'Audit trail',
  auditTrailSubtitle: 'Latest admin mutations and operational events.',
  launchGate: 'Launch gate',
  launchGateSubtitle: 'The one-week Play Store launch readiness list.',
  usersCopied: '{label} copied',
  copyFailed: 'Copy failed',
  usersCsvExported: 'Users CSV exported',
  auditCsvExported: 'Audit CSV exported',
  exportUnavailable: 'Export unavailable',
  launchHandoff: 'Launch handoff',
  adminChangesSaved: 'Admin changes saved',
  adminChangesFailed: 'Admin changes failed',
  maintenanceSaved: 'Maintenance control saved',
  maintenanceFailed: 'Maintenance control failed',
  planSaved: 'Plan catalog saved',
  planFailed: 'Plan catalog failed to save',
  catalogSaved: 'Catalog request saved',
  catalogFailed: 'Catalog request failed',
  aiDeepScanLimits: '{ai} AI / {deep} deep / {scans} AI scans daily',
  planLimitsPending: 'plan limits pending',
  customPrice: 'Custom',
  usersLabel: 'users',
  generalInfo: 'General info',
  accessSecurity: 'Access & security',
  auditLogs: 'Audit logs',
  launchChecklist: 'Launch checklist',
} as const;


export type AdminCopyKey = keyof typeof EN_ADMIN_COPY;

const ID_ADMIN_COPY: Record<AdminCopyKey, string> = {
  accessRequiredTitle: 'Akses admin diperlukan',
  accessRequiredAuth: 'Masuk dengan akun owner untuk membuka konsol manajemen.',
  accessRequiredForbidden: 'Akun saat ini belum terdaftar di ADMIN_EMAILS atau ADMIN_USER_IDS.',
  adminRequestFailed: 'Permintaan admin gagal',
  signIn: 'Masuk',
  retry: 'Coba lagi',
  dismissAdminError: 'Tutup error admin',
  pageTitle: 'Manajemen Admin',
  pageSubtitle: 'Kelola user, plan, database, audit, dan kontrol launching.',
  skipToAdminContent: 'Lewati ke konten admin',
  adminNavigation: 'Navigasi admin',
  adminContent: 'Konten admin',
  mobileAdminDock: 'Bar komando admin mobile',
  attentionItems: 'item perlu perhatian',
  backToApp: 'Aplikasi',
  backToAppTitle: 'Kembali ke aplikasi',
  switchToLight: 'Ubah admin ke mode terang',
  switchToDark: 'Ubah admin ke mode gelap',
  light: 'Terang',
  dark: 'Gelap',
  refresh: 'Muat ulang',
  live: 'Live',
  livePaused: 'Live dijeda',
  tabOverview: 'Komando',
  tabUsers: 'User',
  tabPlans: 'Plan',
  tabQueues: 'Antrean',
  tabAi: 'Kontrol AI',
  tabMaintenance: 'Maintenance',
  tabDatabase: 'Database',
  tabRecipes: 'Recipe Library',
  tabAudit: 'Audit',
  tabLaunch: 'Launching',
  metricTotalUsers: 'Total User',
  metricPaidUsers: 'User Berbayar',
  metricAiToday: 'AI Hari Ini',
  metricLaunchGate: 'Gate Launching',
  activeAccounts: '{count} akun aktif',
  planConversion: '{count}% konversi plan',
  deepRequests: '{count} request deep',
  criticalWarnings: 'Gagal kritis / peringatan',
  exportTitle: 'Paket export operator',
  exportSubtitle: 'Unduh daftar akun, audit trail, atau salin ringkasan handoff launching untuk support dan founder.',
  usersCsv: 'CSV User',
  auditCsv: 'CSV Audit',
  copyHandoff: 'Salin handoff',
  snapshot: 'Snapshot',
  freshness: 'Kesegaran',
  queues: 'Antrean',
  flags: 'Flag',
  queueRisk: 'Antrean risiko',
  queueRecovery: 'Antrean recovery',
  queueBilling: 'Perhatian billing',
  queuePaid: 'User berbayar',
  queueSample: 'Data preview',
  queueAll: 'Semua antrean',
  paymentQueuesTitle: 'Antrean payment dan plan',
  paymentQueuesSubtitle: 'Review invoice manual, upload bukti, entitlement tertunda, dan user billing yang perlu perhatian dari satu antrean compact.',
  paymentQueueSearchLabel: 'Cari antrean payment',
  paymentQueueSearchPlaceholder: 'Cari invoice, email, user, plan, bank, path bukti',
  paymentQueueResults: '{shown} dari {total} request payment tampil',
  paymentQueueEmpty: 'Tidak ada request pembayaran manual yang cocok.',
  paymentQueueAll: 'Semua',
  paymentQueuePending: 'Menunggu',
  paymentQueueReceipt: 'Bukti diterima',
  paymentQueueVerified: 'Terverifikasi',
  paymentQueueRejected: 'Ditolak',
  paymentQueueExpired: 'Expired',
  paymentQueueBuyer: 'Pembeli',
  paymentQueueTransfer: 'Transfer',
  paymentQueueProof: 'Bukti',
  paymentQueueActions: 'Verifikasi hanya setelah nominal, rekening, dan bukti dicek.',
  paymentQueueOpenProof: 'Lihat bukti',
  paymentQueueOpenUser: 'Buka user',
  paymentQueuePlanUsers: 'User plan dan billing perlu perhatian',
  paymentQueuePlanUsersSubtitle: 'User dengan entitlement, renewal, past-due, atau status pembayaran manual yang perlu review admin.',
  paymentQueueNoBillingUsers: 'Tidak ada user billing yang perlu perhatian sekarang.',
  paymentQueueKpiManual: 'Manual terbuka',
  paymentQueueKpiProof: 'Antrean bukti',
  paymentQueueKpiPlan: 'User plan',
  paymentQueueKpiClosed: 'Review selesai',
  commandCenterTitle: 'Pusat komando operasional',
  commandCenterSubtitle: 'Antrean prioritas untuk support akun, blocker launching, dan respons maintenance live.',
  riskCardTitle: 'Antrean risiko',
  riskCardDetail: '{count} past-due plus akun suspended atau berisiko tinggi.',
  recoveryCardTitle: 'Recovery',
  recoveryCardDetail: 'Reset password dan permintaan pemulihan akun.',
  billingCardTitle: 'Billing',
  billingCardDetail: 'Review pembayaran, refund, expired, dan past-due.',
  flagsCardTitle: 'Flag',
  flagsCardDetail: 'Kontrol maintenance aktif untuk web, PWA, mobile, atau admin.',
  paidCardTitle: 'Berbayar',
  paidCardDetail: 'Akun Starter, Pro, Team, dan Enterprise.',
  handoffTitle: 'Handoff operator',
  noUrgentHandoff: 'Tidak ada handoff mendesak',
  queuesClear: 'Antrean risiko dan recovery bersih.',
  productionChecks: 'Pemeriksaan production',
  productionChecksSubtitle: 'Kesiapan backend, database, billing, dan AI saat ini.',
  planMix: 'Komposisi plan',
  recommendations: 'Rekomendasi',
  userFilters: 'Filter user',
  usersSearchLabel: 'Cari user',
  clearSearch: 'Bersihkan pencarian',
  clearFilters: 'Reset filter',
  queueFilterLabel: 'Filter antrean',
  statusFilterLabel: 'Filter status',
  planFilterLabel: 'Filter plan',
  recoveryFilterLabel: 'Filter recovery',
  userResultsSummary: '{shown} dari {total} user tampil',
  selectedUserSummary: 'Dipilih: {name}',
  selectUserHint: 'Pilih user untuk membuka kontrol akun.',
  userCardControls: 'Kontrol kartu user',
  usersTableCaption: 'Tabel manajemen user dengan kontrol akun, plan, billing, role, recovery, pemakaian, risiko, dan terakhir aktif.',
  usersSearchPlaceholder: 'Cari nama, username, email, atau user id',
  allStatus: 'Semua status',
  allPlans: 'Semua plan',
  allRecovery: 'Semua recovery',
  noMatchingUsers: 'Tidak ada user cocok',
  noMatchingUsersSubtitle: 'Sesuaikan pencarian, status, atau filter plan.',
  account: 'Akun',
  status: 'Status',
  plan: 'Plan',
  billing: 'Billing',
  role: 'Role',
  recovery: 'Recovery',
  usageToday: 'Pemakaian hari ini',
  risk: 'Risiko',
  lastSeen: 'Terakhir aktif',
  manage: 'Kelola',
  preview: 'preview',
  unassigned: 'belum diisi',
  unknown: 'Tidak diketahui',
  localeNA: 'locale belum ada',
  actionRequired: 'Butuh tindakan',
  passwordResetRequired: 'Reset password wajib',
  saving: 'Menyimpan...',
  savingAccount: 'Menyimpan akun...',
  accountControl: 'Kontrol akun',
  closeAccountPanel: 'Tutup panel akun',
  created: 'Dibuat',
  currentPlan: 'Plan saat ini',
  displayName: 'Nama tampil',
  username: 'Username',
  adminQuickActions: 'Aksi cepat admin',
  adminQuickActionsSubtitle: 'Gunakan untuk flow support launching yang sering dipakai tanpa mencari setiap field.',
  restoreActive: 'Pulihkan aktif',
  suspendReview: 'Suspend untuk review',
  planQuickControl: 'Kontrol plan cepat',
  planQuickControlSubtitle: 'Pilih tier, lihat kuota, lalu terapkan entitlement dengan catatan support siap audit.',
  provider: 'Provider',
  market: 'Market',
  manualReview: 'review manual',
  selected: 'dipilih',
  applyProvisional: 'Terapkan sementara',
  applyFree: 'Terapkan gratis',
  billingEntitlement: 'Billing dan entitlement',
  receiptModeDetail: 'Mode receipt menerapkan {limit} langsung, lalu tetap meminta review manual sampai langganan diverifikasi.',
  billingStatus: 'Status billing',
  paymentActionRequired: 'Tindakan pembayaran wajib',
  receiptReceived: 'Receipt diterima',
  markPaid: 'Tandai paid',
  markPastDue: 'Tandai past due',
  billingPeriodStart: 'Mulai billing',
  billingPeriodEnd: 'Akhir billing',
  pastDueDate: 'Tanggal past due',
  contactUserWhatsApp: 'Kontak user',
  paymentSupportWhatsApp: 'Support payment',
  whatsapp: 'WhatsApp',
  customer: 'Customer',
  subscription: 'Subscription',
  renewsEnds: 'Perpanjang/berakhir {date}',
  requirePasswordReset: 'Wajibkan reset password',
  internalNotes: 'Catatan internal',
  supportNote: 'Catatan support',
  entitlementNeedsNote: 'Entitlement berbayar butuh catatan support minimal 12 karakter sebelum disimpan.',
  saveAccount: 'Simpan akun',
  requestReset: 'Minta reset',
  resolveRecovery: 'Selesaikan recovery',
  confirmAccountChange: 'Konfirmasi perubahan akun',
  confirmAccountChangeDetail: 'Perubahan ini memengaruhi akses akun atau status support.',
  confirmChange: 'Konfirmasi perubahan',
  confirmDeletion: 'Konfirmasi status akun dihapus',
  confirmDeletionDetail: 'Ini menandai akun sebagai dihapus dan memblokir akses aplikasi normal.',
  markDeleted: 'Tandai dihapus',
  confirmSuspension: 'Konfirmasi suspend akun',
  confirmSuspensionDetail: 'Ini memblokir akses Baristachaw normal sampai dipulihkan.',
  suspendAccount: 'Suspend akun',
  confirmRoleChange: 'Konfirmasi perubahan role penting',
  confirmRoleChangeDetail: 'Role owner dan admin memengaruhi siapa yang bisa mengelola user, plan, dan kontrol launching.',
  operatorReview: 'Review operator',
  operatorReason: 'Alasan operator',
  required: 'wajib',
  operatorReasonRequiredPlaceholder: 'Alasan perubahan akses akun ini',
  operatorReasonOptionalPlaceholder: 'Catatan opsional untuk riwayat support',
  savedToSupportNote: '{count}/220 tersimpan ke catatan support',
  cancel: 'Batal',
  confirmFeatureDisable: 'Konfirmasi fitur dinonaktifkan',
  confirmMaintenanceMode: 'Konfirmasi mode maintenance',
  featureChangeDetail: 'Perubahan ini mengatur ketersediaan permukaan Baristachaw dan harus punya pesan operator yang jelas.',
  cancelFeatureChange: 'Batalkan perubahan feature flag',
  userImpact: 'Dampak user',
  userImpactDetail: 'User di permukaan terpilih bisa melihat fitur diblokir atau terdegradasi sampai flag kembali tersedia.',
  operatorMessageRequired: 'Pesan operator wajib',
  maintenanceMessagePlaceholder: 'Alasan maintenance atau disable yang terlihat oleh user',
  savedToMaintenanceMessage: '{count}/240 tersimpan ke pesan maintenance',
  disableFeature: 'Nonaktifkan fitur',
  applyMaintenance: 'Terapkan maintenance',
  paymentReadiness: 'Kesiapan pembayaran',
  active: 'aktif',
  pastDue: 'past due',
  connectedProviders: 'Provider terhubung',
  notConfigured: 'belum dikonfigurasi',
  marketsPrepared: 'Market siap: {markets}.',
  realtimeContract: 'Kontrak realtime',
  planCatalog: 'Katalog plan',
  planCatalogSubtitle: 'Tier komersial, batas kuota, mapping provider, entitlement ID, dan kesiapan billing launching.',
  reset: 'Reset',
  save: 'Simpan',
  name: 'Nama',
  displayPrice: 'Harga tampil',
  description: 'Deskripsi',
  priceUsd: 'Harga USD',
  aiDay: 'AI/hari',
  deepDay: 'Deep/hari',
  scansDay: 'Limit AI Scanner/hari',
  storageMb: 'Storage MB',
  seats: 'Seat',
  slaHours: 'Jam SLA',
  checkout: 'Checkout',
  productId: 'Product ID',
  priceId: 'Price ID',
  entitlementId: 'Entitlement ID',
  features: 'Fitur',
  paymentMethods: 'Metode pembayaran',
  recommended: 'Direkomendasikan',
  pendingChanges: '{count} perubahan menunggu',
  noPendingChanges: 'Tidak ada perubahan',
  operatorNote: 'Catatan operator',
  operatorNotePlaceholder: 'Alasan operator untuk audit trail',
  numericFieldsInvalid: 'Angka harus aman untuk plan: harga/kuota tidak boleh negatif, seat dan SLA minimal 1.',
  pricingOperations: 'Operasi harga',
  pricingOperationsSubtitle: 'Kelola harga plan dinamis dan kode promo yang dipakai checkout billing.',
  dynamicPricing: 'Harga dinamis',
  dynamicPricingSubtitle: 'Baris aktif menggantikan harga katalog statis di kartu plan dan checkout.',
  promoCodes: 'Kode promo',
  promoCodesSubtitle: 'Aturan voucher divalidasi server sebelum diskon checkout diterapkan.',
  addPrice: 'Tambah harga',
  addPromo: 'Tambah promo',
  edit: 'Edit',
  delete: 'Hapus',
  duration: 'Durasi',
  currency: 'Mata uang',
  originalPrice: 'Harga awal',
  discountPrice: 'Harga diskon',
  inactive: 'nonaktif',
  savePrice: 'Simpan harga',
  savePromo: 'Simpan promo',
  promoCode: 'Kode promo',
  discountType: 'Jenis diskon',
  discountValue: 'Nilai diskon',
  maxUses: 'Batas pakai',
  validUntil: 'Berlaku sampai',
  validPlanCodes: 'Plan berlaku',
  validDurations: 'Durasi berlaku',
  percentageDiscount: 'Persentase',
  fixedAmountDiscount: 'Nominal tetap',
  discount: 'Diskon',
  currentUses: 'Pemakaian',
  exhausted: 'habis',
  activePricesEmpty: 'Belum ada harga custom aktif. Harga katalog statis tetap dipakai.',
  promosEmpty: 'Belum ada kode promo.',
  operatorNoteRequired: 'Catatan operator minimal 12 karakter.',
  priceValidationRequired: 'Plan, durasi, mata uang, dan harga awal wajib diisi.',
  promoValidationRequired: 'Kode promo, jenis diskon, dan nilai diskon wajib diisi.',
  deletePriceTitle: 'Hapus harga plan',
  deletePromoTitle: 'Hapus kode promo',
  deletePriceDescription: 'Hapus {item}? Checkout akan kembali memakai harga katalog statis.',
  deletePromoDescription: 'Hapus {item}? Kode promo ini tidak bisa dipakai lagi saat checkout.',
  confirmDelete: 'Hapus',
  maintenanceControls: 'Kontrol maintenance',
  maintenanceControlsSubtitle: 'Feature availability flag yang dipakai web, PWA, dan sesi Android parity.',
  aiProviderControls: 'Kontrol provider AI',
  aiProviderControlsSubtitle: 'Pantau kesehatan provider sisi server, kesiapan pool key, prioritas fallback, dan kontrol admin tanpa membuka API key.',
  aiProviderSecurityNote: 'Nilai API key tidak pernah dikirim ke browser. Admin hanya melihat jumlah key, status, model, dan kode error yang sudah disanitasi.',
  aiProviderReady: 'Chain AI siap',
  aiEnabledProviders: 'Provider aktif',
  aiConfiguredProviders: 'Provider ber-key',
  aiPaidCreditProviders: 'Pool paid credit',
  aiStandardKeys: 'Key standar',
  aiPaidKeys: 'Key paid',
  aiPrimaryModel: 'Model utama',
  aiRecommendedFor: 'Dipakai untuk',
  aiLastHealth: 'Health terakhir',
  aiNoKeys: 'Belum ada server key',
  aiFallbackPolicy: 'Fallback chain dikontrol admin',
  aiNoSecretLeak: 'Inventory aman secret',
  aiBrewUsageTitle: 'Pemakaian provider AI Brew',
  aiBrewUsageSubtitle: 'Melacak provider/model AI online yang benar-benar dipakai AI Brew, bukan fallback planner lokal atau klik tombol generate.',
  aiBrewFallbackTitle: 'Fallback rate AI Brew',
  aiBrewFallbackSubtitle: 'Menghitung kejadian optimizer ditolak/no-change dan fallback sequence yang dilaporkan client production.',
  aiBrewFallbackRate: 'Fallback rate',
  aiBrewFallbackOptimizerRejected: 'Optimizer ditolak',
  aiBrewFallbackNoChange: 'No-change dipakai',
  aiBrewFallbackSequence: 'Fallback sequence',
  aiBrewFallbackRecent: 'Event fallback terbaru',
  aiBrewFallbackNoEvents: 'Belum ada event fallback AI Brew yang terekam.',
  aiBrewFallbackThreshold: 'Ambang alert',
  aiBrewFallbackTrend: 'Tren 7 hari',
  aiUsageToday: 'Hari ini',
  aiUsageMonth: 'Bulan ini',
  aiUsageCustom: 'Range custom',
  aiUsageTokens: 'Token',
  aiUsageCost: 'Estimasi biaya',
  aiUsageFailures: 'Gagal',
  aiUsageLatency: 'Rata-rata latency',
  aiUsageEstimated: 'Estimasi',
  aiUsageFrom: 'Dari',
  aiUsageTo: 'Sampai',
  aiUsageApply: 'Terapkan range',
  aiUsageProviderBreakdown: 'Pemakaian provider bulan ini',
  aiUsageRecentEvents: 'Panggilan AI Brew terbaru',
  aiUsageNoEvents: 'Belum ada panggilan AI Brew online yang terekam.',
  userFacingMaintenanceMessage: 'Pesan maintenance untuk user',
  savingMaintenanceControl: 'Menyimpan kontrol maintenance...',
  databaseReadiness: 'Kesiapan database',
  databaseReadinessSubtitle: 'Persistence, RLS, audit, dan kontrol plan untuk operasi production.',
  catalogOperations: 'Operasi katalog',
  catalogOperationsSubtitle: 'Antrean review water, dripper, dan grinder.',
  recipeLibrary: 'Recipe Library',
  recipeLibrarySubtitle: 'Plan AI Brew, recipe Collection, dan catatan rasa yang tersinkron dari user login.',
  recipeLibrarySynced: 'Item tersinkron',
  recipeLibraryAiBrew: 'Plan AI Brew',
  recipeLibraryCollection: 'Recipe Collection',
  recipeLibraryFeedback: 'Catatan rasa',
  recipeLibraryRecent: 'Recipe tersimpan terbaru',
  recipeLibraryNoItems: 'Belum ada recipe tersinkron.',
  recipeLibraryGap: 'Gap sync recipe',
  recipeLibraryReady: 'Recipe library siap',
  queuedCount: '{count} antre',
  needsSourceCount: '{count} butuh sumber',
  approvedCount: '{count} disetujui',
  noCatalogRequests: 'Belum ada request katalog.',
  newCatalogRequest: 'Request katalog baru',
  queue: 'Antrekan',
  kind: 'Jenis',
  title: 'Judul',
  entityId: 'Entity ID',
  sourceUrl: 'Source URL',
  payloadJson: 'Payload JSON',
  payloadMustObject: 'Payload harus berupa object JSON.',
  payloadInvalid: 'Payload JSON tidak valid.',
  auditTrail: 'Audit trail',
  auditTrailSubtitle: 'Mutasi admin dan event operasional terbaru.',
  launchGate: 'Gate launching',
  launchGateSubtitle: 'Daftar kesiapan launching Play Store satu minggu.',
  usersCopied: '{label} tersalin',
  copyFailed: 'Gagal menyalin',
  usersCsvExported: 'CSV user berhasil diexport',
  auditCsvExported: 'CSV audit berhasil diexport',
  exportUnavailable: 'Export tidak tersedia',
  launchHandoff: 'Handoff launching',
  adminChangesSaved: 'Perubahan admin tersimpan',
  adminChangesFailed: 'Perubahan admin gagal',
  maintenanceSaved: 'Kontrol maintenance tersimpan',
  maintenanceFailed: 'Kontrol maintenance gagal',
  planSaved: 'Katalog plan tersimpan',
  planFailed: 'Katalog plan gagal disimpan',
  catalogSaved: 'Request katalog tersimpan',
  catalogFailed: 'Request katalog gagal',
  aiDeepScanLimits: '{ai} AI / {deep} deep / {scans} scan AI per hari',
  planLimitsPending: 'limit plan belum siap',
  customPrice: 'Custom',
  usersLabel: 'user',
  generalInfo: 'Informasi umum',
  accessSecurity: 'Akses & keamanan',
  auditLogs: 'Log audit',
  launchChecklist: 'Checklist launching',
};


const PARTIAL_ADMIN_COPY: Partial<Record<Language, Partial<Record<AdminCopyKey, string>>>> = {
  ar: {
    pageTitle: 'إدارة المشرف',
    pageSubtitle: 'إدارة المستخدمين والخطط وقاعدة البيانات والتدقيق والإطلاق.',
    tabOverview: 'التحكم',
    tabUsers: 'المستخدمون',
    tabPlans: 'الخطط',
    tabMaintenance: 'الصيانة',
    tabDatabase: 'قاعدة البيانات',
    tabAudit: 'التدقيق',
    tabLaunch: 'الإطلاق',
    manage: 'إدارة',
    accountControl: 'التحكم بالحساب',
    planCatalog: 'كتالوج الخطط',
    operatorNote: 'ملاحظة المشغل',
    catalogOperations: 'عمليات الكتالوج',
    newCatalogRequest: 'طلب كتالوج جديد',
    payloadJson: 'Payload JSON',
    save: 'حفظ',
    queue: 'إضافة للانتظار',
    refresh: 'تحديث',
    light: 'فاتح',
    dark: 'داكن',
  },
  zh: {
    pageTitle: '管理员管理',
    pageSubtitle: '管理用户、套餐、数据库、审计和发布控制。',
    tabOverview: '指挥台',
    tabUsers: '用户',
    tabPlans: '套餐',
    tabMaintenance: '维护',
    tabDatabase: '数据库',
    tabAudit: '审计',
    tabLaunch: '发布',
    manage: '管理',
    accountControl: '账户控制',
    planCatalog: '套餐目录',
    operatorNote: '操作员备注',
    catalogOperations: '目录操作',
    newCatalogRequest: '新目录请求',
    save: '保存',
    queue: '加入队列',
    refresh: '刷新',
  },
  ja: {
    pageTitle: '管理コンソール',
    pageSubtitle: 'ユーザー、プラン、データベース、監査、ローンチ管理。',
    tabOverview: 'コマンド',
    tabUsers: 'ユーザー',
    tabPlans: 'プラン',
    tabMaintenance: 'メンテナンス',
    tabDatabase: 'データベース',
    tabAudit: '監査',
    tabLaunch: 'ローンチ',
    manage: '管理',
    accountControl: 'アカウント管理',
    planCatalog: 'プランカタログ',
    operatorNote: 'オペレーターメモ',
    catalogOperations: 'カタログ操作',
    newCatalogRequest: '新規カタログ申請',
    save: '保存',
    queue: 'キューへ追加',
    refresh: '更新',
  },
  ko: {
    pageTitle: '관리자 관리',
    pageSubtitle: '사용자, 플랜, 데이터베이스, 감사, 출시 제어를 관리합니다.',
    tabOverview: '지휘',
    tabUsers: '사용자',
    tabPlans: '플랜',
    tabMaintenance: '점검',
    tabDatabase: '데이터베이스',
    tabAudit: '감사',
    tabLaunch: '출시',
    manage: '관리',
    accountControl: '계정 제어',
    planCatalog: '플랜 카탈로그',
    operatorNote: '운영자 메모',
    catalogOperations: '카탈로그 작업',
    newCatalogRequest: '새 카탈로그 요청',
    save: '저장',
    queue: '대기열 추가',
    refresh: '새로고침',
  },
  th: {
    pageTitle: 'จัดการผู้ดูแล',
    pageSubtitle: 'จัดการผู้ใช้ แผน ฐานข้อมูล การตรวจสอบ และการเปิดตัว',
    tabOverview: 'ศูนย์ควบคุม',
    tabUsers: 'ผู้ใช้',
    tabPlans: 'แผน',
    tabMaintenance: 'บำรุงรักษา',
    tabDatabase: 'ฐานข้อมูล',
    tabAudit: 'ตรวจสอบ',
    tabLaunch: 'เปิดตัว',
    manage: 'จัดการ',
    accountControl: 'ควบคุมบัญชี',
    planCatalog: 'แคตตาล็อกแผน',
    operatorNote: 'บันทึกผู้ดูแล',
    catalogOperations: 'งานแคตตาล็อก',
    newCatalogRequest: 'คำขอแคตตาล็อกใหม่',
    save: 'บันทึก',
    queue: 'เข้าคิว',
    refresh: 'รีเฟรช',
  },
  vi: {
    pageTitle: 'Quản lý Admin',
    pageSubtitle: 'Quản lý người dùng, gói, cơ sở dữ liệu, kiểm toán và phát hành.',
    tabOverview: 'Điều phối',
    tabUsers: 'Người dùng',
    tabPlans: 'Gói',
    tabMaintenance: 'Bảo trì',
    tabDatabase: 'Cơ sở dữ liệu',
    tabAudit: 'Kiểm toán',
    tabLaunch: 'Phát hành',
    manage: 'Quản lý',
    accountControl: 'Điều khiển tài khoản',
    planCatalog: 'Danh mục gói',
    operatorNote: 'Ghi chú vận hành',
    catalogOperations: 'Vận hành danh mục',
    newCatalogRequest: 'Yêu cầu danh mục mới',
    save: 'Lưu',
    queue: 'Xếp hàng',
    refresh: 'Làm mới',
  },
  ms: {
    pageTitle: 'Pengurusan Admin',
    pageSubtitle: 'Urus pengguna, pelan, pangkalan data, audit, dan kawalan pelancaran.',
    tabOverview: 'Komando',
    tabUsers: 'Pengguna',
    tabPlans: 'Pelan',
    tabMaintenance: 'Penyelenggaraan',
    tabDatabase: 'Pangkalan data',
    tabAudit: 'Audit',
    tabLaunch: 'Pelancaran',
    manage: 'Urus',
    accountControl: 'Kawalan akaun',
    planCatalog: 'Katalog pelan',
    operatorNote: 'Nota operator',
    catalogOperations: 'Operasi katalog',
    newCatalogRequest: 'Permintaan katalog baharu',
    save: 'Simpan',
    queue: 'Masuk giliran',
    refresh: 'Segar semula',
  },
};

const EN_ENUM_LABELS: Record<string, string> = {
  pass: 'Pass',
  warn: 'Warning',
  fail: 'Fail',
  active: 'Active',
  trialing: 'Trialing',
  past_due: 'Past due',
  suspended: 'Suspended',
  deleted: 'Deleted',
  none: 'None',
  requested: 'Requested',
  verified: 'Verified',
  resolved: 'Resolved',
  rejected: 'Rejected',
  cancelled: 'Cancelled',
  expired: 'Expired',
  refunded: 'Refunded',
  available: 'Available',
  maintenance: 'Maintenance',
  disabled: 'Disabled',
  selected: 'Selected',
  owner: 'Owner',
  admin: 'Admin',
  support: 'Support',
  analyst: 'Analyst',
  user: 'User',
  free: 'Free',
  starter: 'Starter',
  pro: 'Pro',
  team: 'Team',
  enterprise: 'Enterprise',
  monthly: 'Monthly',
  quarterly: 'Quarterly',
  yearly: 'Yearly',
  lifetime: 'Lifetime',
  manual: 'Manual',
  admin_provider: 'Admin',
  google_play: 'Google Play',
  app_store: 'App Store',
  stripe: 'Stripe',
  revenuecat: 'RevenueCat',
  indonesia: 'Indonesia',
  brunei: 'Brunei',
  global: 'Global',
  unknown: 'Unknown',
  disabled_checkout: 'Disabled',
  external: 'External',
  stripe_checkout: 'Stripe Checkout',
  play_billing: 'Play Billing',
  manual_invoice: 'Manual invoice',
  grinder: 'Grinder',
  water: 'Water',
  dripper: 'Dripper',
  web: 'Web',
  pwa: 'PWA',
  mobile: 'Mobile',
  global_surface: 'Global',
  sample: 'Sample',
  supabase: 'Supabase',
  preview: 'Preview',
  live: 'Live',
};

const ID_ENUM_LABELS: Record<string, string> = {
  pass: 'Lolos',
  warn: 'Peringatan',
  fail: 'Gagal',
  active: 'Aktif',
  trialing: 'Trial',
  past_due: 'Terlambat bayar',
  suspended: 'Suspended',
  deleted: 'Dihapus',
  none: 'Tidak ada',
  requested: 'Diminta',
  verified: 'Terverifikasi',
  resolved: 'Selesai',
  rejected: 'Ditolak',
  cancelled: 'Dibatalkan',
  expired: 'Expired',
  refunded: 'Refunded',
  available: 'Tersedia',
  maintenance: 'Maintenance',
  disabled: 'Nonaktif',
  selected: 'Dipilih',
  owner: 'Owner',
  admin: 'Admin',
  support: 'Support',
  analyst: 'Analis',
  user: 'User',
  free: 'Gratis',
  starter: 'Starter',
  pro: 'Pro',
  team: 'Team',
  enterprise: 'Enterprise',
  monthly: 'Bulanan',
  quarterly: 'Triwulan',
  yearly: 'Tahunan',
  lifetime: 'Lifetime',
  manual: 'Manual',
  admin_provider: 'Admin',
  google_play: 'Google Play',
  app_store: 'App Store',
  stripe: 'Stripe',
  revenuecat: 'RevenueCat',
  indonesia: 'Indonesia',
  brunei: 'Brunei',
  global: 'Global',
  unknown: 'Tidak diketahui',
  disabled_checkout: 'Nonaktif',
  external: 'External',
  stripe_checkout: 'Stripe Checkout',
  play_billing: 'Play Billing',
  manual_invoice: 'Invoice manual',
  grinder: 'Grinder',
  water: 'Water',
  dripper: 'Dripper',
  web: 'Web',
  pwa: 'PWA',
  mobile: 'Mobile',
  global_surface: 'Global',
  sample: 'Sample',
  supabase: 'Supabase',
  preview: 'Preview',
  live: 'Live',
};

const PARTIAL_ENUM_LABELS: Partial<Record<Language, Record<string, string>>> = {
  id: ID_ENUM_LABELS,
  ms: {
    pass: 'Lulus',
    warn: 'Amaran',
    fail: 'Gagal',
    active: 'Aktif',
    trialing: 'Percubaan',
    past_due: 'Tertunggak',
    suspended: 'Digantung',
    deleted: 'Dipadam',
    available: 'Tersedia',
    maintenance: 'Penyelenggaraan',
    disabled: 'Dilumpuhkan',
    selected: 'Dipilih',
  },
};

function normalizeLanguage(value?: string | null): Language {
  const short = String(value || '').trim().toLowerCase().split(/[-_]/)[0];
  return isSupportedLanguage(short) ? short : DEFAULT_LANGUAGE;
}

function fallbackLabel(value: string): string {
  return value.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function formatTemplate(template: string, params: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (token, key) => (
    Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : token
  ));
}

export function createAdminCopy(language?: Language | string | null) {
  const normalizedLanguage = normalizeLanguage(language);
  const locale = getLanguageLocale(normalizedLanguage);
  const copy = {
    ...EN_ADMIN_COPY,
    ...(normalizedLanguage === 'id' ? ID_ADMIN_COPY : PARTIAL_ADMIN_COPY[normalizedLanguage]),
  } as Record<AdminCopyKey, string>;
  const enumLabels = {
    ...EN_ENUM_LABELS,
    ...(PARTIAL_ENUM_LABELS[normalizedLanguage] || {}),
  };

  return {
    language: normalizedLanguage,
    locale,
    text(key: AdminCopyKey) {
      return copy[key] || EN_ADMIN_COPY[key] || key;
    },
    format(key: AdminCopyKey, params?: Record<string, string | number>) {
      return formatTemplate(copy[key] || EN_ADMIN_COPY[key] || key, params);
    },
    enumLabel(value: string) {
      const enumKey = value === 'admin' ? 'admin' : value === 'global' ? 'global_surface' : value;
      return enumLabels[enumKey] || fallbackLabel(value);
    },
    number(value: number) {
      return new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(value);
    },
    currencyUsd(value: number) {
      if (value <= 0) return copy.customPrice;
      return new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value);
    },
    date(value: string) {
      const date = new Date(value);
      if (Number.isNaN(date.getTime())) return copy.unknown;
      return new Intl.DateTimeFormat(locale, {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }).format(date);
    },
    raw: copy,
  };
}

export type AdminCopy = ReturnType<typeof createAdminCopy>;
