import type { BrewMethodId, BrewMethodProfile } from './types.ts';
import { getMethodEvidenceProfile } from './evidence/pack.ts';

const RAW_BREW_METHOD_PROFILES: BrewMethodProfile[] = [
  {
    id: 'espresso',
    label: 'Espresso',
    category: 'espresso',
    recommendedRatios: [1, 1.5, 2, 2.5, 3],
    ratioPolicy: {
      min: 1,
      max: 3.5,
      label: 'espresso shot baseline',
    },
    shotPresets: [
      {
        id: 'ristretto',
        label: 'Ristretto',
        ratio: 1.3,
        ratioRange: { min: 1, max: 1.5 },
        timeSeconds: { min: 20, max: 28 },
      },
      {
        id: 'espresso',
        label: 'Espresso',
        ratio: 2,
        ratioRange: { min: 1.8, max: 2.2 },
        timeSeconds: { min: 25, max: 32 },
      },
      {
        id: 'lungo',
        label: 'Lungo',
        ratio: 2.8,
        ratioRange: { min: 2.5, max: 3.5 },
        timeSeconds: { min: 30, max: 40 },
      },
      {
        id: 'doppio',
        label: 'Doppio',
        ratio: 2,
        ratioRange: { min: 1.8, max: 2.2 },
        timeSeconds: { min: 26, max: 34 },
      },
    ],
    ratioDefault: 2,
    ratioRange: [1, 3.5],
    tempRangeC: [90, 96],
    brewTimeRangeSec: [20, 40],
    retentionFactor: 0,
    processLossMl: 0,
    grindGuidance: 'Fine, adjust by shot time and flow',
    scaNotes: 'Espresso profile with shot-style targets for repeatable dial-in and service consistency.',
  },
  {
    id: 'v60',
    label: 'V60',
    category: 'filter',
    recommendedRatios: [15, 15.5, 16, 16.5, 17],
    ratioDefault: 16,
    ratioRange: [14.5, 17.5],
    tempRangeC: [90, 96],
    brewTimeRangeSec: [150, 240],
    retentionFactor: 2.2,
    processLossMl: 8,
    grindGuidance: 'Medium-fine, even bed drawdown',
    scaNotes: 'SCA-style filter range with balanced clarity and sweetness.',
  },
  {
    id: 'v60_japanese_iced',
    label: 'V60 Iced Brew',
    category: 'filter',
    recommendedRatios: [14, 14.5, 15, 15.5, 16],
    ratioDefault: 15,
    ratioRange: [13.5, 16.5],
    tempRangeC: [91, 96],
    brewTimeRangeSec: [150, 240],
    retentionFactor: 2.1,
    processLossMl: 10,
    grindGuidance: 'Medium-fine, slightly tighter than hot V60',
    scaNotes: 'Brew strong over ice to preserve aroma and clarity.',
    japaneseSplit: {
      hotWaterShare: 0.6,
      iceShare: 0.4,
    },
  },
  {
    id: 'chemex',
    label: 'Chemex',
    category: 'filter',
    recommendedRatios: [15.5, 16, 16.5, 17, 17.5],
    ratioDefault: 16.5,
    ratioRange: [15, 18],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [205, 275],
    retentionFactor: 2.4,
    processLossMl: 12,
    grindGuidance: 'Medium-coarse for thicker filter paper',
    scaNotes: 'Thick bonded paper needs a hard rinse, warm glass, open vent, and a longer stable finish than V60.',
  },
  {
    id: 'chemex_iced',
    label: 'Chemex Iced Brew',
    category: 'filter',
    recommendedRatios: [14.5, 15, 15.5, 16, 16.5],
    ratioDefault: 15.4,
    ratioRange: [14, 16.8],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [180, 260],
    retentionFactor: 2.4,
    processLossMl: 12,
    grindGuidance: 'Medium-coarse, keep the thicker filter open over ice',
    scaNotes: 'Hot concentrate over measured ice only; protect thick-paper flow and avoid late bypass water.',
    japaneseSplit: {
      hotWaterShare: 0.64,
      iceShare: 0.36,
    },
  },
  {
    id: 'kalita_wave',
    label: 'Kalita Wave',
    category: 'filter',
    recommendedRatios: [15, 15.5, 16, 16.5, 17],
    ratioDefault: 16,
    ratioRange: [15, 17.5],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [180, 270],
    retentionFactor: 2.2,
    processLossMl: 8,
    grindGuidance: 'Medium grind, flat-bed consistency',
    scaNotes: 'Flat-bed extraction: center-to-small-ring pours, level bed, no wide circular agitation.',
  },
  {
    id: 'kalita_wave_iced',
    label: 'Kalita Wave Iced Brew',
    category: 'filter',
    recommendedRatios: [14.5, 15, 15.5, 16, 16.5],
    ratioDefault: 15.2,
    ratioRange: [14, 16.8],
    tempRangeC: [89, 94],
    brewTimeRangeSec: [165, 250],
    retentionFactor: 2.2,
    processLossMl: 9,
    grindGuidance: 'Medium, keep the flat bed level through compact iced pulses',
    scaNotes: 'Flat-bottom iced profile tuned for stable sweetness and low bypass.',
    japaneseSplit: {
      hotWaterShare: 0.61,
      iceShare: 0.39,
    },
  },
  {
    id: 'melitta',
    label: 'Melitta',
    category: 'filter',
    recommendedRatios: [14.5, 15, 15.5, 16, 16.5],
    ratioDefault: 15.7,
    ratioRange: [14.5, 17],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [185, 280],
    retentionFactor: 2.3,
    processLossMl: 9,
    grindGuidance: 'Medium, steady trapezoid flow with even bed coverage',
    scaNotes: 'Forgiving trapezoid filter profile with stable middle contact and tidy finish.',
  },
  {
    id: 'melitta_iced',
    label: 'Melitta Iced Brew',
    category: 'filter',
    recommendedRatios: [14, 14.5, 15, 15.5, 16],
    ratioDefault: 14.9,
    ratioRange: [13.8, 16.4],
    tempRangeC: [89, 94],
    brewTimeRangeSec: [165, 245],
    retentionFactor: 2.3,
    processLossMl: 10,
    grindGuidance: 'Medium, measured trapezoid pours over ice',
    scaNotes: 'Iced trapezoid profile that keeps sweetness steady without flattening the cup.',
    japaneseSplit: {
      hotWaterShare: 0.62,
      iceShare: 0.38,
    },
  },
  {
    id: 'french_press',
    label: 'French Press',
    category: 'filter',
    recommendedRatios: [13, 14, 15, 15.5, 16],
    ratioDefault: 15,
    ratioRange: [12, 16],
    tempRangeC: [91, 96],
    brewTimeRangeSec: [240, 360],
    retentionFactor: 2.6,
    processLossMl: 10,
    grindGuidance: 'Coarse, low fines',
    scaNotes: 'Immersion workflow: charge, steep, let fines settle, then decant to stop extraction.',
  },
  {
    id: 'aeropress',
    label: 'AeroPress',
    category: 'filter',
    recommendedRatios: [12, 13, 14, 15, 16],
    ratioDefault: 14,
    ratioRange: [11, 17],
    tempRangeC: [80, 94],
    brewTimeRangeSec: [60, 150],
    retentionFactor: 1.9,
    processLossMl: 6,
    grindGuidance: 'Medium-fine (varies with recipe/inversion)',
    scaNotes: 'Pressure-assisted immersion: style-specific steep, stir count, press duration, and stop-before-hiss cue.',
  },
  {
    id: 'clever_dripper',
    label: 'Clever Dripper',
    category: 'filter',
    recommendedRatios: [14.5, 15, 15.5, 16, 16.5],
    ratioDefault: 15.5,
    ratioRange: [14, 17],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [150, 240],
    retentionFactor: 2.2,
    processLossMl: 8,
    grindGuidance: 'Medium to medium-coarse',
    scaNotes: 'Steep-and-release workflow first; charge with valve closed, hold immersion, then release cleanly.',
  },
  {
    id: 'clever_dripper_iced',
    label: 'Clever Dripper Iced Brew',
    category: 'filter',
    recommendedRatios: [14, 14.5, 15, 15.5, 16],
    ratioDefault: 15,
    ratioRange: [13.8, 16.4],
    tempRangeC: [89, 94],
    brewTimeRangeSec: [150, 240],
    retentionFactor: 2.2,
    processLossMl: 9,
    grindGuidance: 'Medium to medium-coarse, keep immersion calm before release',
    scaNotes: 'Iced Clever profile that preserves sweetness before a clean release over ice.',
    japaneseSplit: {
      hotWaterShare: 0.63,
      iceShare: 0.37,
    },
  },
  {
    id: 'origami',
    label: 'Origami',
    category: 'filter',
    recommendedRatios: [15, 15.5, 16, 16.5, 17],
    ratioDefault: 15.8,
    ratioRange: [14.5, 17],
    tempRangeC: [90, 96],
    brewTimeRangeSec: [150, 250],
    retentionFactor: 2.2,
    processLossMl: 8,
    grindGuidance: 'Medium-fine, tuned to filter choice',
    scaNotes: 'High agility dripper with cone/flat filter options.',
  },
  {
    id: 'origami_iced',
    label: 'Origami Iced Brew',
    category: 'filter',
    recommendedRatios: [14, 14.5, 15, 15.5, 16],
    ratioDefault: 15.1,
    ratioRange: [13.8, 16.4],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [145, 225],
    retentionFactor: 2.2,
    processLossMl: 9,
    grindGuidance: 'Medium-fine, agile pulses with compact flow over ice',
    scaNotes: 'Iced Origami profile for crisp aromatics and quick, clean cone flow.',
    japaneseSplit: {
      hotWaterShare: 0.59,
      iceShare: 0.41,
    },
  },
  {
    id: 'april',
    label: 'April',
    category: 'filter',
    recommendedRatios: [16, 16.5, 17, 17.5, 18],
    ratioDefault: 17,
    ratioRange: [15.5, 18.5],
    tempRangeC: [88, 94],
    brewTimeRangeSec: [150, 230],
    retentionFactor: 2.1,
    processLossMl: 7,
    grindGuidance: 'Medium, lower agitation style',
    scaNotes: 'Designed around lower-temp, controlled extraction.',
  },
  {
    id: 'april_iced',
    label: 'April Iced Brew',
    category: 'filter',
    recommendedRatios: [15.5, 16, 16.5, 17, 17.5],
    ratioDefault: 16.2,
    ratioRange: [15, 17.8],
    tempRangeC: [87, 93],
    brewTimeRangeSec: [140, 215],
    retentionFactor: 2.1,
    processLossMl: 8,
    grindGuidance: 'Medium, fast low-agitation pulses over ice',
    scaNotes: 'Iced April profile tuned for low-agitation sweetness and fast service flow.',
    japaneseSplit: {
      hotWaterShare: 0.58,
      iceShare: 0.42,
    },
  },
  {
    id: 'kono',
    label: 'Kono',
    category: 'filter',
    recommendedRatios: [14.5, 15, 15.5, 16, 16.5],
    ratioDefault: 15.7,
    ratioRange: [14.5, 17],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [180, 265],
    retentionFactor: 2.2,
    processLossMl: 8,
    grindGuidance: 'Medium-fine, centered pours with longer middle contact',
    scaNotes: 'Sweet-center cone profile with longer contact through the middle of the brew.',
  },
  {
    id: 'kono_iced',
    label: 'Kono Iced Brew',
    category: 'filter',
    recommendedRatios: [14, 14.5, 15, 15.5, 16],
    ratioDefault: 15,
    ratioRange: [13.8, 16.4],
    tempRangeC: [90, 95],
    brewTimeRangeSec: [155, 235],
    retentionFactor: 2.2,
    processLossMl: 9,
    grindGuidance: 'Medium-fine, tighter centered pours for sweet iced contact',
    scaNotes: 'Iced Kono profile tuned to keep the center sweet before dilution lands in the cup.',
    japaneseSplit: {
      hotWaterShare: 0.61,
      iceShare: 0.39,
    },
  },
  {
    id: 'siphon',
    label: 'Siphon',
    category: 'filter',
    recommendedRatios: [14, 14.5, 15, 15.5, 16],
    ratioDefault: 15,
    ratioRange: [13, 16.5],
    tempRangeC: [90, 94],
    brewTimeRangeSec: [180, 300],
    retentionFactor: 2.3,
    processLossMl: 10,
    grindGuidance: 'Medium',
    scaNotes: 'Vacuum workflow: heat, draw-up, add coffee, stir briefly, extract, remove heat, then drawdown.',
  },
  {
    id: 'moka_pot',
    label: 'Moka Pot',
    category: 'filter',
    recommendedRatios: [8, 9, 10, 11, 12],
    ratioDefault: 10,
    ratioRange: [7, 12],
    tempRangeC: [88, 95],
    brewTimeRangeSec: [120, 240],
    retentionFactor: 1.8,
    processLossMl: 14,
    grindGuidance: 'Medium-fine (between espresso and filter)',
    scaNotes: 'Stovetop workflow: level basket, boiler water below valve, moderate heat, stop before sputter.',
  },
  {
    id: 'cold_brew',
    label: 'Cold Brew',
    category: 'filter',
    recommendedRatios: [10, 12, 14, 16, 18],
    ratioDefault: 14,
    ratioRange: [8, 18],
    tempRangeC: [4, 25],
    brewTimeRangeSec: [21600, 64800],
    retentionFactor: 2.7,
    processLossMl: 12,
    grindGuidance: 'Coarse',
    scaNotes: 'Cold immersion workflow: cool-water saturation, long steep, clean filtration, then dilute after brewing if needed.',
  },
  {
    id: 'batch_brew',
    label: 'Batch Brew',
    category: 'batch',
    recommendedRatios: [15.5, 16, 16.5, 17, 17.5],
    ratioDefault: 16.5,
    ratioRange: [15, 18],
    tempRangeC: [90, 96],
    brewTimeRangeSec: [240, 360],
    retentionFactor: 2.2,
    processLossMl: 14,
    grindGuidance: 'Medium, optimized for machine flow rate',
    scaNotes: 'Machine workflow: dose per liter, brew volume, spray distribution, drawdown, and batch mixing before service.',
  },
];

export const BREW_METHOD_PROFILES: BrewMethodProfile[] = RAW_BREW_METHOD_PROFILES.map((profile) => {
  const evidence = getMethodEvidenceProfile(profile.id);
  if (!evidence) return profile;
  return {
    ...profile,
    ratioDefault: evidence.baseline.ratioDefault,
    ratioRange: evidence.baseline.ratioRange,
    tempRangeC: evidence.baseline.tempRangeC,
    brewTimeRangeSec: evidence.baseline.brewTimeRangeSec,
    ratioPolicy: evidence.ratioPolicy,
    roastSupport: evidence.roastSupport,
    roastAdjustments: evidence.roastAdjustments ?? profile.roastAdjustments,
  };
});

export const BREW_METHOD_MAP: Record<BrewMethodId, BrewMethodProfile> = BREW_METHOD_PROFILES.reduce(
  (acc, profile) => {
    acc[profile.id] = profile;
    return acc;
  },
  {} as Record<BrewMethodId, BrewMethodProfile>
);
